// Map i18n language codes to Edge TTS voice names
export const LANGUAGE_VOICE_MAP: Record<string, string> = {
  en: 'en-US-AriaNeural',
  hr: 'hr-HR-GabrijelaNeural',
  de: 'de-DE-KatjaNeural',
  fr: 'fr-FR-DeniseNeural',
  es: 'es-ES-ElviraNeural',
  it: 'it-IT-ElsaNeural',
  pt: 'pt-BR-FranciscaNeural',
  nl: 'nl-NL-ColetteNeural',
  pl: 'pl-PL-AgnieszkaNeural',
  cs: 'cs-CZ-VlastaNeural',
  sk: 'sk-SK-ViktoriaNeural',
  sl: 'sl-SI-PetraNeural',
  sr: 'sr-RS-SophieNeural',
  bs: 'bs-BA-VesnaNeural',
  ja: 'ja-JP-NanamiNeural',
  ko: 'ko-KR-SunHiNeural',
  zh: 'zh-CN-XiaoxiaoNeural',
  ru: 'ru-RU-SvetlanaNeural',
  uk: 'uk-UA-PolinaNeural',
  tr: 'tr-TR-EmelNeural',
  ar: 'ar-SA-ZariyahNeural',
  hi: 'hi-IN-SwaraNeural',
};
