"""
Integration tests for the OpenAI-compatible API surface.

Endpoints (all on the Kotlin backend, reached through the gateway):
    GET  /api/v1/models
    GET  /api/v1/models/{id}
    POST /api/v1/chat/completions          # SSE when stream=True, JSON otherwise

Auth: Authorization: Bearer scp-... (an API key generated by
POST /api/v1/auth/api-keys). The legacy X-API-Key header still works for
existing CLI users; this test exercises the Bearer path because that is what
the openai-python and openai-js SDKs send.

Coverage:
  * GET  /v1/models       lists workspaces and collections as model ids
  * POST /v1/chat/completions stream=False returns a chat.completion JSON
  * POST /v1/chat/completions stream=True  returns SSE with [DONE] terminator
  * Auth: missing Bearer → 401
  * Slug routing: unknown workspace slug → 404
"""

from __future__ import annotations

import json
import uuid

import pytest
import requests

from tests.conftest import GATEWAY_URL

# --------------------------------------------------------------------------- #
# Per-test fixtures (NOT session-scoped — each test gets a fresh API key so a  #
# failure in one test does not leave behind state that pollutes the next).     #
# --------------------------------------------------------------------------- #


@pytest.fixture
def api_key(authenticated_session: requests.Session) -> str:
    """Mint a Scrapalot API key via the existing /auth/api-keys endpoint."""
    name = f"openai-compat-test-{uuid.uuid4().hex[:8]}"
    response = authenticated_session.post(
        f"{GATEWAY_URL}/auth/api-keys",
        json={"name": name},
        timeout=30,
    )
    assert response.status_code == 201, f"Failed to create API key: {response.status_code} {response.text}"
    payload = response.json()
    plain = payload.get("plainTextKey") or payload.get("plain_text_key")
    assert plain and plain.startswith("scp-"), f"Expected scp-... plaintext key, got: {payload}"
    yield plain

    # Best-effort cleanup so the user's key list does not bloat across runs.
    key_id = payload.get("id")
    if key_id:
        authenticated_session.delete(f"{GATEWAY_URL}/auth/api-keys/{key_id}", timeout=15)


@pytest.fixture
def openai_session(api_key: str) -> requests.Session:
    """A bare requests session that authenticates exactly like the OpenAI SDK."""
    s = requests.Session()
    s.headers.update({"Authorization": f"Bearer {api_key}"})
    return s


# --------------------------------------------------------------------------- #
# /v1/models                                                                  #
# --------------------------------------------------------------------------- #


@pytest.mark.integration
def test_v1_models_lists_workspaces(openai_session: requests.Session, test_workspace: dict):
    """GET /v1/models returns the OpenAI list envelope and includes the test workspace."""
    response = openai_session.get(f"{GATEWAY_URL}/models", timeout=15)
    assert response.status_code == 200, response.text

    body = response.json()
    assert body["object"] == "list"
    assert isinstance(body["data"], list) and body["data"], "Expected at least the test workspace in /v1/models"

    ids = {entry["id"] for entry in body["data"]}
    workspace_slug = test_workspace.get("slug")
    if workspace_slug:
        assert f"scrapalot:{workspace_slug}" in ids, f"Expected scrapalot:{workspace_slug} in /v1/models, got {sorted(ids)[:10]}"

    for entry in body["data"]:
        assert entry["object"] == "model"
        assert entry["owned_by"] == "scrapalot"
        assert isinstance(entry["created"], int)


# --------------------------------------------------------------------------- #
# /v1/chat/completions — non-streaming                                        #
# --------------------------------------------------------------------------- #


@pytest.mark.integration
def test_chat_completions_non_stream(openai_session: requests.Session, test_workspace: dict):
    """POST stream=False → single chat.completion JSON with assistant content."""
    workspace_slug = test_workspace.get("slug") or "default"
    response = openai_session.post(
        f"{GATEWAY_URL}/chat/completions",
        json={
            "model": f"scrapalot:{workspace_slug}",
            "messages": [{"role": "user", "content": "Reply with exactly the word: PONG"}],
            "stream": False,
        },
        timeout=120,
    )
    assert response.status_code == 200, response.text

    body = response.json()
    assert body["object"] == "chat.completion"
    assert body["model"] == f"scrapalot:{workspace_slug}"
    assert body["id"].startswith("chatcmpl-"), body["id"]

    choices = body["choices"]
    assert len(choices) == 1
    msg = choices[0]["message"]
    assert msg["role"] == "assistant"
    assert isinstance(msg["content"], str) and msg["content"].strip(), "Assistant content must not be empty"


# --------------------------------------------------------------------------- #
# /v1/chat/completions — streaming                                            #
# --------------------------------------------------------------------------- #


@pytest.mark.integration
def test_chat_completions_stream(openai_session: requests.Session, test_workspace: dict):
    """POST stream=True → SSE chunks ending with `data: [DONE]`."""
    workspace_slug = test_workspace.get("slug") or "default"
    response = openai_session.post(
        f"{GATEWAY_URL}/chat/completions",
        json={
            "model": f"scrapalot:{workspace_slug}",
            "messages": [{"role": "user", "content": "Reply with exactly the word: PONG"}],
            "stream": True,
        },
        stream=True,
        timeout=120,
        headers={"Accept": "text/event-stream"},
    )
    assert response.status_code == 200, response.text
    assert response.headers["Content-Type"].startswith("text/event-stream"), response.headers

    chunks: list[dict] = []
    saw_done = False
    saw_finish_stop = False

    for raw in response.iter_lines(decode_unicode=True):
        if not raw or not raw.startswith("data:"):
            continue
        payload = raw[len("data:") :].strip()
        if payload == "[DONE]":
            saw_done = True
            break
        chunk = json.loads(payload)
        assert chunk["object"] == "chat.completion.chunk"
        chunks.append(chunk)
        if (chunk["choices"][0].get("finish_reason")) == "stop":
            saw_finish_stop = True

    assert chunks, "Expected at least one chat.completion.chunk before [DONE]"
    assert saw_done, "Stream did not terminate with `data: [DONE]`"
    assert saw_finish_stop, "No chunk carried finish_reason=stop"

    # Reconstruct the assistant text from delta.content fragments.
    text = "".join(c["choices"][0]["delta"].get("content") or "" for c in chunks)
    assert text.strip(), f"Empty assistant text reconstructed from chunks: {chunks!r}"


# --------------------------------------------------------------------------- #
# Auth + slug error paths                                                     #
# --------------------------------------------------------------------------- #


@pytest.mark.integration
def test_chat_completions_requires_bearer():
    """No Authorization header → 401, not 500."""
    response = requests.post(
        f"{GATEWAY_URL}/chat/completions",
        json={"model": "scrapalot:default", "messages": [{"role": "user", "content": "hi"}]},
        timeout=15,
    )
    assert response.status_code in (401, 403), response.text


@pytest.mark.integration
def test_chat_completions_scrapalot_extras_passthrough(
    openai_session: requests.Session,
    test_workspace: dict,
    test_collection: dict,
):
    """`scrapalot.collection_ids` overrides slug-resolved collection — proves
    the extras block reaches OpenAICompatibleService.buildChatRequest and
    passes into ChatService.generateChat without losing the routing target.
    """
    workspace_slug = test_workspace.get("slug") or "default"
    response = openai_session.post(
        f"{GATEWAY_URL}/chat/completions",
        json={
            "model": f"scrapalot:{workspace_slug}",
            "messages": [{"role": "user", "content": "Reply with exactly the word: PONG"}],
            "stream": False,
            "scrapalot": {
                # Force RAG against this specific collection even though the
                # model slug points at the workspace root.
                "collection_ids": [str(test_collection["id"])],
                "top_k": 5,
                "similarity_threshold": 0.4,
            },
        },
        timeout=120,
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["object"] == "chat.completion"
    assert body["choices"][0]["message"]["content"].strip(), "Empty assistant content with extras passthrough"


@pytest.mark.integration
def test_chat_completions_stream_passthrough_scrapalot_packets(
    openai_session: requests.Session,
    test_workspace: dict,
    test_collection: dict,
):
    """Stream against a collection (RAG) must emit at least one
    `delta.scrapalot` chunk (citation_info / status / etc.) on top of the
    token stream — proves PR1 packet passthrough works end-to-end.
    """
    workspace_slug = test_workspace.get("slug") or "default"
    response = openai_session.post(
        f"{GATEWAY_URL}/chat/completions",
        json={
            "model": f"scrapalot:{workspace_slug}",
            "messages": [{"role": "user", "content": "What is the main theme of the document?"}],
            "stream": True,
            "scrapalot": {"collection_ids": [str(test_collection["id"])]},
        },
        stream=True,
        timeout=180,
        headers={"Accept": "text/event-stream"},
    )
    assert response.status_code == 200, response.text

    saw_scrapalot_packet = False
    saw_done = False
    for raw in response.iter_lines(decode_unicode=True):
        if not raw or not raw.startswith("data:"):
            continue
        payload = raw[len("data:") :].strip()
        if payload == "[DONE]":
            saw_done = True
            break
        chunk = json.loads(payload)
        delta = chunk["choices"][0].get("delta") or {}
        if isinstance(delta.get("scrapalot"), dict):
            saw_scrapalot_packet = True

    assert saw_done, "Stream did not terminate with [DONE]"
    assert saw_scrapalot_packet, "Expected at least one delta.scrapalot chunk in RAG stream (citation_info/status/etc.)"


@pytest.mark.integration
def test_chat_completions_unknown_workspace_slug(openai_session: requests.Session):
    """Unknown workspace slug → 404 with OpenAI-shaped error envelope."""
    response = openai_session.post(
        f"{GATEWAY_URL}/chat/completions",
        json={
            "model": "scrapalot:does-not-exist-xyz",
            "messages": [{"role": "user", "content": "hi"}],
            "stream": False,
        },
        timeout=30,
    )
    assert response.status_code == 404, response.text
    body = response.json()
    assert "error" in body and body["error"]["type"] == "not_found"
