# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import admin_pb2 as admin__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub:
    """Admin service for debug operations (Docker logs, GitHub workflows).
    These operations require Python container access.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerAutofix = channel.unary_unary(
                '/scrapalot.admin.AdminService/TriggerAutofix',
                request_serializer=admin__pb2.TriggerAutofixRequest.SerializeToString,
                response_deserializer=admin__pb2.TriggerAutofixResponse.FromString,
                _registered_method=True)
        self.GetDebugLogs = channel.unary_unary(
                '/scrapalot.admin.AdminService/GetDebugLogs',
                request_serializer=admin__pb2.GetDebugLogsRequest.SerializeToString,
                response_deserializer=admin__pb2.GetDebugLogsResponse.FromString,
                _registered_method=True)
        self.RebuildGraph = channel.unary_unary(
                '/scrapalot.admin.AdminService/RebuildGraph',
                request_serializer=admin__pb2.RebuildGraphRequest.SerializeToString,
                response_deserializer=admin__pb2.RebuildGraphResponse.FromString,
                _registered_method=True)
        self.RebuildCrossBookRelationships = channel.unary_unary(
                '/scrapalot.admin.AdminService/RebuildCrossBookRelationships',
                request_serializer=admin__pb2.RebuildCrossBookRequest.SerializeToString,
                response_deserializer=admin__pb2.RebuildCrossBookResponse.FromString,
                _registered_method=True)
        self.RelinkDocumentCooccurrence = channel.unary_unary(
                '/scrapalot.admin.AdminService/RelinkDocumentCooccurrence',
                request_serializer=admin__pb2.RelinkDocumentCooccurrenceRequest.SerializeToString,
                response_deserializer=admin__pb2.RelinkDocumentCooccurrenceResponse.FromString,
                _registered_method=True)
        self.GraphHealthCheck = channel.unary_unary(
                '/scrapalot.admin.AdminService/GraphHealthCheck',
                request_serializer=admin__pb2.GraphHealthCheckRequest.SerializeToString,
                response_deserializer=admin__pb2.GraphHealthCheckResponse.FromString,
                _registered_method=True)
        self.SweepGraphOrphans = channel.unary_unary(
                '/scrapalot.admin.AdminService/SweepGraphOrphans',
                request_serializer=admin__pb2.SweepGraphOrphansRequest.SerializeToString,
                response_deserializer=admin__pb2.SweepGraphOrphansResponse.FromString,
                _registered_method=True)
        self.MergeDuplicateEntities = channel.unary_unary(
                '/scrapalot.admin.AdminService/MergeDuplicateEntities',
                request_serializer=admin__pb2.MergeDuplicateEntitiesRequest.SerializeToString,
                response_deserializer=admin__pb2.MergeDuplicateEntitiesResponse.FromString,
                _registered_method=True)
        self.CleanupMissingFileDocs = channel.unary_unary(
                '/scrapalot.admin.AdminService/CleanupMissingFileDocs',
                request_serializer=admin__pb2.CleanupMissingFileDocsRequest.SerializeToString,
                response_deserializer=admin__pb2.CleanupMissingFileDocsResponse.FromString,
                _registered_method=True)
        self.GraphAudit = channel.unary_unary(
                '/scrapalot.admin.AdminService/GraphAudit',
                request_serializer=admin__pb2.GraphAuditRequest.SerializeToString,
                response_deserializer=admin__pb2.GraphAuditResponse.FromString,
                _registered_method=True)
        self.SweepOrphanEntities = channel.unary_unary(
                '/scrapalot.admin.AdminService/SweepOrphanEntities',
                request_serializer=admin__pb2.SweepOrphanEntitiesRequest.SerializeToString,
                response_deserializer=admin__pb2.SweepOrphanEntitiesResponse.FromString,
                _registered_method=True)
        self.EvaluateGraphUtility = channel.unary_unary(
                '/scrapalot.admin.AdminService/EvaluateGraphUtility',
                request_serializer=admin__pb2.EvaluateGraphUtilityRequest.SerializeToString,
                response_deserializer=admin__pb2.EvaluateGraphUtilityResponse.FromString,
                _registered_method=True)
        self.RecomputeEntityIdf = channel.unary_unary(
                '/scrapalot.admin.AdminService/RecomputeEntityIdf',
                request_serializer=admin__pb2.RecomputeEntityIdfRequest.SerializeToString,
                response_deserializer=admin__pb2.RecomputeEntityIdfResponse.FromString,
                _registered_method=True)
        self.GetEntityExtractionMetrics = channel.unary_unary(
                '/scrapalot.admin.AdminService/GetEntityExtractionMetrics',
                request_serializer=admin__pb2.GetEntityExtractionMetricsRequest.SerializeToString,
                response_deserializer=admin__pb2.GetEntityExtractionMetricsResponse.FromString,
                _registered_method=True)
        self.RecomputeCooccurrenceWeights = channel.unary_unary(
                '/scrapalot.admin.AdminService/RecomputeCooccurrenceWeights',
                request_serializer=admin__pb2.RecomputeCooccurrenceWeightsRequest.SerializeToString,
                response_deserializer=admin__pb2.RecomputeCooccurrenceWeightsResponse.FromString,
                _registered_method=True)
        self.PruneCooccurrenceEdges = channel.unary_unary(
                '/scrapalot.admin.AdminService/PruneCooccurrenceEdges',
                request_serializer=admin__pb2.PruneCooccurrenceEdgesRequest.SerializeToString,
                response_deserializer=admin__pb2.PruneCooccurrenceEdgesResponse.FromString,
                _registered_method=True)
        self.RecomputePageRank = channel.unary_unary(
                '/scrapalot.admin.AdminService/RecomputePageRank',
                request_serializer=admin__pb2.RecomputePageRankRequest.SerializeToString,
                response_deserializer=admin__pb2.RecomputePageRankResponse.FromString,
                _registered_method=True)
        self.ClassifyTypedRelationships = channel.unary_unary(
                '/scrapalot.admin.AdminService/ClassifyTypedRelationships',
                request_serializer=admin__pb2.ClassifyTypedRelationshipsRequest.SerializeToString,
                response_deserializer=admin__pb2.ClassifyTypedRelationshipsResponse.FromString,
                _registered_method=True)
        self.RecomputeCollectionFingerprints = channel.unary_unary(
                '/scrapalot.admin.AdminService/RecomputeCollectionFingerprints',
                request_serializer=admin__pb2.RecomputeCollectionFingerprintsRequest.SerializeToString,
                response_deserializer=admin__pb2.RecomputeCollectionFingerprintsResponse.FromString,
                _registered_method=True)
        self.DetectCollectionBridge = channel.unary_unary(
                '/scrapalot.admin.AdminService/DetectCollectionBridge',
                request_serializer=admin__pb2.DetectCollectionBridgeRequest.SerializeToString,
                response_deserializer=admin__pb2.DetectCollectionBridgeResponse.FromString,
                _registered_method=True)
        self.BuildCommunities = channel.unary_unary(
                '/scrapalot.admin.AdminService/BuildCommunities',
                request_serializer=admin__pb2.BuildCommunitiesRequest.SerializeToString,
                response_deserializer=admin__pb2.BuildCommunitiesResponse.FromString,
                _registered_method=True)
        self.GetCommunityHierarchy = channel.unary_unary(
                '/scrapalot.admin.AdminService/GetCommunityHierarchy',
                request_serializer=admin__pb2.GetCommunityHierarchyRequest.SerializeToString,
                response_deserializer=admin__pb2.GetCommunityHierarchyResponse.FromString,
                _registered_method=True)
        self.GetCommunityReport = channel.unary_unary(
                '/scrapalot.admin.AdminService/GetCommunityReport',
                request_serializer=admin__pb2.GetCommunityReportRequest.SerializeToString,
                response_deserializer=admin__pb2.GetCommunityReportResponse.FromString,
                _registered_method=True)
        self.RunHarnessComparison = channel.unary_unary(
                '/scrapalot.admin.AdminService/RunHarnessComparison',
                request_serializer=admin__pb2.RunHarnessComparisonRequest.SerializeToString,
                response_deserializer=admin__pb2.RunHarnessComparisonResponse.FromString,
                _registered_method=True)
        self.GetHarnessComparison = channel.unary_unary(
                '/scrapalot.admin.AdminService/GetHarnessComparison',
                request_serializer=admin__pb2.GetHarnessComparisonRequest.SerializeToString,
                response_deserializer=admin__pb2.GetHarnessComparisonResponse.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """Admin service for debug operations (Docker logs, GitHub workflows).
    These operations require Python container access.
    """

    def TriggerAutofix(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDebugLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebuildGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebuildCrossBookRelationships(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RelinkDocumentCooccurrence(self, request, context):
        """7.8 v3 prereq — re-run per-document CO_OCCURS_WITH creation for
        every completed document in a collection. Fixes the case where
        entity extraction completed earlier but produced zero cooccur
        edges (e.g. before the cypher-direction bug in
        graph_relationship_linker._create_cooccurrence_from_graph was
        fixed). Idempotent — uses MERGE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphHealthCheck(self, request, context):
        """Graph housekeeping — read-only health report and destructive cleanup ops.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SweepGraphOrphans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeDuplicateEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupMissingFileDocs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GraphAudit(self, request, context):
        """Baseline census — read-only audit returning a structured snapshot
        (volume, ratios, duplicates, orphans, RAG usage, pain-point checks) plus
        a pre-rendered markdown report.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SweepOrphanEntities(self, request, context):
        """Sweep `:Entity` nodes with no edges, optional `created_before_days`
        floor and a per-call deletion cap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateGraphUtility(self, request, context):
        """Run the graph-utility evaluation harness against an eval set
        (JSONL) and return aggregated metrics per configuration plus a
        pre-rendered markdown report.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecomputeEntityIdf(self, request, context):
        """On-demand IDF recompute for all `:Entity` nodes. Normally
        runs nightly via Celery beat; this rpc is the admin-panel button.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityExtractionMetrics(self, request, context):
        """Aggregated per-phase timing + LLM cost accounting from
        entity_extraction_metrics. Read-only; populated by phase_timer in the
        extraction pipeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecomputeCooccurrenceWeights(self, request, context):
        """Recompute structured weights on every CO_OCCURS_WITH edge.
        Nightly beat runs this at 04:00 UTC; this rpc is the admin-panel button.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PruneCooccurrenceEdges(self, request, context):
        """Delete low-weight CO_OCCURS_WITH edges and snapshot them to
        Redis for 30 days. `dry_run=true` returns the candidate distribution
        without deleting. Percentile of 0 falls back to config default (0.10).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecomputePageRank(self, request, context):
        """Compute PageRank centrality for documents in a single
        collection (or all eligible collections if collection_id is blank).
        Persists scores to documents.pagerank_score.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyTypedRelationships(self, request, context):
        """Run the LLM typed-relationship classifier on one
        document's top-N entity pairs. Writes IS_A / PART_OF / INFLUENCES /
        CONTRADICTS / SYNONYM_OF typed edges with source_chunks provenance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecomputeCollectionFingerprints(self, request, context):
        """Recompute per-collection fingerprints (centroid +
        top_entities + coverage). Empty collection_id → full nightly pass.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectCollectionBridge(self, request, context):
        """Detect whether a set of collections qualifies for
        bridge mode (distant centroids + shared entities). Read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildCommunities(self, request, context):
        """Hierarchical Leiden communities + LLM reports for one
        collection. Admin-triggered build; nightly beat handles automated reruns.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunityHierarchy(self, request, context):
        """Read-only fetch of the persisted community hierarchy
        for one collection (level → list of communities with title / size / rating).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommunityReport(self, request, context):
        """Full report (title, summary, rating, rating_explanation,
        findings, member entity ids) for one community. Drives the Communities tab
        side panel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunHarnessComparison(self, request, context):
        """Cross-factorial harness
        comparison. Kick off the (retriever × delivery_mode × prompt_variant)
        grid runner against the supplied eval-set sample. Returns the run_id
        immediately; the run executes asynchronously via asyncio.create_task.
        CI deploy-window guard runs internally — when active jobs / graph syncs
        are in flight, the run is recorded with status "blocked_deploy_window"
        and no cells are executed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHarnessComparison(self, request, context):
        """Companion to RunHarnessComparison — admin UI polls this until status
        transitions to "done" / "failed" / "blocked_deploy_window" and renders
        the summary table from the aggregated JSON.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerAutofix': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerAutofix,
                    request_deserializer=admin__pb2.TriggerAutofixRequest.FromString,
                    response_serializer=admin__pb2.TriggerAutofixResponse.SerializeToString,
            ),
            'GetDebugLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDebugLogs,
                    request_deserializer=admin__pb2.GetDebugLogsRequest.FromString,
                    response_serializer=admin__pb2.GetDebugLogsResponse.SerializeToString,
            ),
            'RebuildGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.RebuildGraph,
                    request_deserializer=admin__pb2.RebuildGraphRequest.FromString,
                    response_serializer=admin__pb2.RebuildGraphResponse.SerializeToString,
            ),
            'RebuildCrossBookRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.RebuildCrossBookRelationships,
                    request_deserializer=admin__pb2.RebuildCrossBookRequest.FromString,
                    response_serializer=admin__pb2.RebuildCrossBookResponse.SerializeToString,
            ),
            'RelinkDocumentCooccurrence': grpc.unary_unary_rpc_method_handler(
                    servicer.RelinkDocumentCooccurrence,
                    request_deserializer=admin__pb2.RelinkDocumentCooccurrenceRequest.FromString,
                    response_serializer=admin__pb2.RelinkDocumentCooccurrenceResponse.SerializeToString,
            ),
            'GraphHealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphHealthCheck,
                    request_deserializer=admin__pb2.GraphHealthCheckRequest.FromString,
                    response_serializer=admin__pb2.GraphHealthCheckResponse.SerializeToString,
            ),
            'SweepGraphOrphans': grpc.unary_unary_rpc_method_handler(
                    servicer.SweepGraphOrphans,
                    request_deserializer=admin__pb2.SweepGraphOrphansRequest.FromString,
                    response_serializer=admin__pb2.SweepGraphOrphansResponse.SerializeToString,
            ),
            'MergeDuplicateEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeDuplicateEntities,
                    request_deserializer=admin__pb2.MergeDuplicateEntitiesRequest.FromString,
                    response_serializer=admin__pb2.MergeDuplicateEntitiesResponse.SerializeToString,
            ),
            'CleanupMissingFileDocs': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupMissingFileDocs,
                    request_deserializer=admin__pb2.CleanupMissingFileDocsRequest.FromString,
                    response_serializer=admin__pb2.CleanupMissingFileDocsResponse.SerializeToString,
            ),
            'GraphAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.GraphAudit,
                    request_deserializer=admin__pb2.GraphAuditRequest.FromString,
                    response_serializer=admin__pb2.GraphAuditResponse.SerializeToString,
            ),
            'SweepOrphanEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.SweepOrphanEntities,
                    request_deserializer=admin__pb2.SweepOrphanEntitiesRequest.FromString,
                    response_serializer=admin__pb2.SweepOrphanEntitiesResponse.SerializeToString,
            ),
            'EvaluateGraphUtility': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateGraphUtility,
                    request_deserializer=admin__pb2.EvaluateGraphUtilityRequest.FromString,
                    response_serializer=admin__pb2.EvaluateGraphUtilityResponse.SerializeToString,
            ),
            'RecomputeEntityIdf': grpc.unary_unary_rpc_method_handler(
                    servicer.RecomputeEntityIdf,
                    request_deserializer=admin__pb2.RecomputeEntityIdfRequest.FromString,
                    response_serializer=admin__pb2.RecomputeEntityIdfResponse.SerializeToString,
            ),
            'GetEntityExtractionMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityExtractionMetrics,
                    request_deserializer=admin__pb2.GetEntityExtractionMetricsRequest.FromString,
                    response_serializer=admin__pb2.GetEntityExtractionMetricsResponse.SerializeToString,
            ),
            'RecomputeCooccurrenceWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.RecomputeCooccurrenceWeights,
                    request_deserializer=admin__pb2.RecomputeCooccurrenceWeightsRequest.FromString,
                    response_serializer=admin__pb2.RecomputeCooccurrenceWeightsResponse.SerializeToString,
            ),
            'PruneCooccurrenceEdges': grpc.unary_unary_rpc_method_handler(
                    servicer.PruneCooccurrenceEdges,
                    request_deserializer=admin__pb2.PruneCooccurrenceEdgesRequest.FromString,
                    response_serializer=admin__pb2.PruneCooccurrenceEdgesResponse.SerializeToString,
            ),
            'RecomputePageRank': grpc.unary_unary_rpc_method_handler(
                    servicer.RecomputePageRank,
                    request_deserializer=admin__pb2.RecomputePageRankRequest.FromString,
                    response_serializer=admin__pb2.RecomputePageRankResponse.SerializeToString,
            ),
            'ClassifyTypedRelationships': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyTypedRelationships,
                    request_deserializer=admin__pb2.ClassifyTypedRelationshipsRequest.FromString,
                    response_serializer=admin__pb2.ClassifyTypedRelationshipsResponse.SerializeToString,
            ),
            'RecomputeCollectionFingerprints': grpc.unary_unary_rpc_method_handler(
                    servicer.RecomputeCollectionFingerprints,
                    request_deserializer=admin__pb2.RecomputeCollectionFingerprintsRequest.FromString,
                    response_serializer=admin__pb2.RecomputeCollectionFingerprintsResponse.SerializeToString,
            ),
            'DetectCollectionBridge': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectCollectionBridge,
                    request_deserializer=admin__pb2.DetectCollectionBridgeRequest.FromString,
                    response_serializer=admin__pb2.DetectCollectionBridgeResponse.SerializeToString,
            ),
            'BuildCommunities': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildCommunities,
                    request_deserializer=admin__pb2.BuildCommunitiesRequest.FromString,
                    response_serializer=admin__pb2.BuildCommunitiesResponse.SerializeToString,
            ),
            'GetCommunityHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunityHierarchy,
                    request_deserializer=admin__pb2.GetCommunityHierarchyRequest.FromString,
                    response_serializer=admin__pb2.GetCommunityHierarchyResponse.SerializeToString,
            ),
            'GetCommunityReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommunityReport,
                    request_deserializer=admin__pb2.GetCommunityReportRequest.FromString,
                    response_serializer=admin__pb2.GetCommunityReportResponse.SerializeToString,
            ),
            'RunHarnessComparison': grpc.unary_unary_rpc_method_handler(
                    servicer.RunHarnessComparison,
                    request_deserializer=admin__pb2.RunHarnessComparisonRequest.FromString,
                    response_serializer=admin__pb2.RunHarnessComparisonResponse.SerializeToString,
            ),
            'GetHarnessComparison': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHarnessComparison,
                    request_deserializer=admin__pb2.GetHarnessComparisonRequest.FromString,
                    response_serializer=admin__pb2.GetHarnessComparisonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.admin.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.admin.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """Admin service for debug operations (Docker logs, GitHub workflows).
    These operations require Python container access.
    """

    @staticmethod
    def TriggerAutofix(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/TriggerAutofix',
            admin__pb2.TriggerAutofixRequest.SerializeToString,
            admin__pb2.TriggerAutofixResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDebugLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/GetDebugLogs',
            admin__pb2.GetDebugLogsRequest.SerializeToString,
            admin__pb2.GetDebugLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebuildGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RebuildGraph',
            admin__pb2.RebuildGraphRequest.SerializeToString,
            admin__pb2.RebuildGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebuildCrossBookRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RebuildCrossBookRelationships',
            admin__pb2.RebuildCrossBookRequest.SerializeToString,
            admin__pb2.RebuildCrossBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RelinkDocumentCooccurrence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RelinkDocumentCooccurrence',
            admin__pb2.RelinkDocumentCooccurrenceRequest.SerializeToString,
            admin__pb2.RelinkDocumentCooccurrenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphHealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/GraphHealthCheck',
            admin__pb2.GraphHealthCheckRequest.SerializeToString,
            admin__pb2.GraphHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SweepGraphOrphans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/SweepGraphOrphans',
            admin__pb2.SweepGraphOrphansRequest.SerializeToString,
            admin__pb2.SweepGraphOrphansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergeDuplicateEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/MergeDuplicateEntities',
            admin__pb2.MergeDuplicateEntitiesRequest.SerializeToString,
            admin__pb2.MergeDuplicateEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupMissingFileDocs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/CleanupMissingFileDocs',
            admin__pb2.CleanupMissingFileDocsRequest.SerializeToString,
            admin__pb2.CleanupMissingFileDocsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GraphAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/GraphAudit',
            admin__pb2.GraphAuditRequest.SerializeToString,
            admin__pb2.GraphAuditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SweepOrphanEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/SweepOrphanEntities',
            admin__pb2.SweepOrphanEntitiesRequest.SerializeToString,
            admin__pb2.SweepOrphanEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateGraphUtility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/EvaluateGraphUtility',
            admin__pb2.EvaluateGraphUtilityRequest.SerializeToString,
            admin__pb2.EvaluateGraphUtilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecomputeEntityIdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RecomputeEntityIdf',
            admin__pb2.RecomputeEntityIdfRequest.SerializeToString,
            admin__pb2.RecomputeEntityIdfResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityExtractionMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/GetEntityExtractionMetrics',
            admin__pb2.GetEntityExtractionMetricsRequest.SerializeToString,
            admin__pb2.GetEntityExtractionMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecomputeCooccurrenceWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RecomputeCooccurrenceWeights',
            admin__pb2.RecomputeCooccurrenceWeightsRequest.SerializeToString,
            admin__pb2.RecomputeCooccurrenceWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PruneCooccurrenceEdges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/PruneCooccurrenceEdges',
            admin__pb2.PruneCooccurrenceEdgesRequest.SerializeToString,
            admin__pb2.PruneCooccurrenceEdgesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecomputePageRank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RecomputePageRank',
            admin__pb2.RecomputePageRankRequest.SerializeToString,
            admin__pb2.RecomputePageRankResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyTypedRelationships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/ClassifyTypedRelationships',
            admin__pb2.ClassifyTypedRelationshipsRequest.SerializeToString,
            admin__pb2.ClassifyTypedRelationshipsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecomputeCollectionFingerprints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RecomputeCollectionFingerprints',
            admin__pb2.RecomputeCollectionFingerprintsRequest.SerializeToString,
            admin__pb2.RecomputeCollectionFingerprintsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectCollectionBridge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/DetectCollectionBridge',
            admin__pb2.DetectCollectionBridgeRequest.SerializeToString,
            admin__pb2.DetectCollectionBridgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildCommunities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/BuildCommunities',
            admin__pb2.BuildCommunitiesRequest.SerializeToString,
            admin__pb2.BuildCommunitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunityHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/GetCommunityHierarchy',
            admin__pb2.GetCommunityHierarchyRequest.SerializeToString,
            admin__pb2.GetCommunityHierarchyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommunityReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/GetCommunityReport',
            admin__pb2.GetCommunityReportRequest.SerializeToString,
            admin__pb2.GetCommunityReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunHarnessComparison(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/RunHarnessComparison',
            admin__pb2.RunHarnessComparisonRequest.SerializeToString,
            admin__pb2.RunHarnessComparisonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHarnessComparison(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.admin.AdminService/GetHarnessComparison',
            admin__pb2.GetHarnessComparisonRequest.SerializeToString,
            admin__pb2.GetHarnessComparisonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
