# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import annotations_pb2 as annotations__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in annotations_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnnotationServiceStub:
    """Annotation service — fetch document and collection annotations from Kotlin backend.
    Kotlin is the owner of annotation data; Python reads via gRPC for RAG context enrichment.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDocumentAnnotations = channel.unary_unary(
                '/scrapalot.annotation.AnnotationService/GetDocumentAnnotations',
                request_serializer=annotations__pb2.GetDocumentAnnotationsRequest.SerializeToString,
                response_deserializer=annotations__pb2.AnnotationListResponse.FromString,
                _registered_method=True)
        self.GetCollectionAnnotations = channel.unary_unary(
                '/scrapalot.annotation.AnnotationService/GetCollectionAnnotations',
                request_serializer=annotations__pb2.GetCollectionAnnotationsRequest.SerializeToString,
                response_deserializer=annotations__pb2.AnnotationListResponse.FromString,
                _registered_method=True)


class AnnotationServiceServicer:
    """Annotation service — fetch document and collection annotations from Kotlin backend.
    Kotlin is the owner of annotation data; Python reads via gRPC for RAG context enrichment.
    """

    def GetDocumentAnnotations(self, request, context):
        """Fetch annotations for a specific document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionAnnotations(self, request, context):
        """Fetch annotations across all documents in a collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnnotationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDocumentAnnotations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentAnnotations,
                    request_deserializer=annotations__pb2.GetDocumentAnnotationsRequest.FromString,
                    response_serializer=annotations__pb2.AnnotationListResponse.SerializeToString,
            ),
            'GetCollectionAnnotations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionAnnotations,
                    request_deserializer=annotations__pb2.GetCollectionAnnotationsRequest.FromString,
                    response_serializer=annotations__pb2.AnnotationListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.annotation.AnnotationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.annotation.AnnotationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnnotationService:
    """Annotation service — fetch document and collection annotations from Kotlin backend.
    Kotlin is the owner of annotation data; Python reads via gRPC for RAG context enrichment.
    """

    @staticmethod
    def GetDocumentAnnotations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.annotation.AnnotationService/GetDocumentAnnotations',
            annotations__pb2.GetDocumentAnnotationsRequest.SerializeToString,
            annotations__pb2.AnnotationListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionAnnotations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.annotation.AnnotationService/GetCollectionAnnotations',
            annotations__pb2.GetCollectionAnnotationsRequest.SerializeToString,
            annotations__pb2.AnnotationListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
