# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: annotations.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'annotations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61nnotations.proto\x12\x14scrapalot.annotation\"Z\n\x1dGetDocumentAnnotationsRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"^\n\x1fGetCollectionAnnotationsRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"k\n\x16\x41nnotationListResponse\x12<\n\x0b\x61nnotations\x18\x01 \x03(\x0b\x32\'.scrapalot.annotation.AnnotationMessage\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"\xcf\x02\n\x11\x41nnotationMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x15\n\rcollection_id\x18\x04 \x01(\t\x12\x17\n\x0f\x61nnotation_type\x18\x05 \x01(\x05\x12\x15\n\rselected_text\x18\x06 \x01(\t\x12\x0f\n\x07\x63omment\x18\x07 \x01(\t\x12\r\n\x05\x63olor\x18\x08 \x01(\t\x12\x12\n\npage_label\x18\t \x01(\t\x12\x15\n\rposition_json\x18\n \x01(\t\x12\x13\n\x0bviewer_type\x18\x0b \x01(\t\x12\x11\n\tis_pinned\x18\x0c \x01(\x08\x12\x12\n\ncreated_at\x18\r \x01(\t\x12\x12\n\nupdated_at\x18\x0e \x01(\t\x12\x12\n\nsession_id\x18\x0f \x01(\t\x12\x12\n\nsort_index\x18\x10 \x01(\t2\x91\x02\n\x11\x41nnotationService\x12{\n\x16GetDocumentAnnotations\x12\x33.scrapalot.annotation.GetDocumentAnnotationsRequest\x1a,.scrapalot.annotation.AnnotationListResponse\x12\x7f\n\x18GetCollectionAnnotations\x12\x35.scrapalot.annotation.GetCollectionAnnotationsRequest\x1a,.scrapalot.annotation.AnnotationListResponseBA\n%com.scrapalot.backend.grpc.annotationB\x16\x41nnotationServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'annotations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.scrapalot.backend.grpc.annotationB\026AnnotationServiceProtoP\001'
  _globals['_GETDOCUMENTANNOTATIONSREQUEST']._serialized_start=43
  _globals['_GETDOCUMENTANNOTATIONSREQUEST']._serialized_end=133
  _globals['_GETCOLLECTIONANNOTATIONSREQUEST']._serialized_start=135
  _globals['_GETCOLLECTIONANNOTATIONSREQUEST']._serialized_end=229
  _globals['_ANNOTATIONLISTRESPONSE']._serialized_start=231
  _globals['_ANNOTATIONLISTRESPONSE']._serialized_end=338
  _globals['_ANNOTATIONMESSAGE']._serialized_start=341
  _globals['_ANNOTATIONMESSAGE']._serialized_end=676
  _globals['_ANNOTATIONSERVICE']._serialized_start=679
  _globals['_ANNOTATIONSERVICE']._serialized_end=952
# @@protoc_insertion_point(module_scope)
