# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import chat_pb2 as chat__pb2
from src.main.grpc import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub:
    """Chat Service - Specialized RPCs for each chat mode
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateDirectLLM = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateDirectLLM',
                request_serializer=chat__pb2.DirectLLMRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GenerateRAG = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateRAG',
                request_serializer=chat__pb2.RAGRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GenerateDeepResearch = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateDeepResearch',
                request_serializer=chat__pb2.DeepResearchRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GenerateWebSearch = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateWebSearch',
                request_serializer=chat__pb2.WebSearchRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GenerateAgenticRAG = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateAgenticRAG',
                request_serializer=chat__pb2.AgenticRAGRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GenerateDocumentQA = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateDocumentQA',
                request_serializer=chat__pb2.DocumentQARequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GenerateTitle = channel.unary_unary(
                '/scrapalot.chat.ChatService/GenerateTitle',
                request_serializer=chat__pb2.TitleRequest.SerializeToString,
                response_deserializer=chat__pb2.TitleResponse.FromString,
                _registered_method=True)
        self.GenerateChat = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateChat',
                request_serializer=chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GenerateChatTutor = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateChatTutor',
                request_serializer=chat__pb2.TutorChatRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.GetTutorProgress = channel.unary_unary(
                '/scrapalot.chat.ChatService/GetTutorProgress',
                request_serializer=chat__pb2.GetTutorProgressRequest.SerializeToString,
                response_deserializer=chat__pb2.TutorProgressResponse.FromString,
                _registered_method=True)
        self.GenerateImage = channel.unary_stream(
                '/scrapalot.chat.ChatService/GenerateImage',
                request_serializer=chat__pb2.GenerateImageRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponsePacket.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/scrapalot.chat.ChatService/HealthCheck',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=chat__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ChatServiceServicer:
    """Chat Service - Specialized RPCs for each chat mode
    """

    def GenerateDirectLLM(self, request, context):
        """Direct LLM chat (no RAG, no collections)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRAG(self, request, context):
        """Traditional RAG with 18 strategies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDeepResearch(self, request, context):
        """5-phase deep research pipeline
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateWebSearch(self, request, context):
        """Web search enhanced chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAgenticRAG(self, request, context):
        """Multi-source agentic RAG orchestration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDocumentQA(self, request, context):
        """Document QA for unprocessed documents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTitle(self, request, context):
        """Title generation (non-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateChat(self, request, context):
        """Deprecated: Use mode-specific RPCs instead
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateChatTutor(self, request, context):
        """7.8 v3 — AI Tutor curriculum mode. Walks the user through Leiden
        communities of a collection one lesson at a time using a state
        machine (lesson_intro → check_understanding → drill_in → quiz →
        lesson_recap). Auto-builds the curriculum on first call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTutorProgress(self, request, context):
        """7.8 v3 — read-only progress for the in-flight tutor session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImage(self, request, context):
        """6.1 — Generate one or more images for a prompt and stream
        ChatResponsePacket(type="image_attached", ...) packets back. The Python
        ImageGenerationOrchestrator picks the right provider/model from the
        user's selection and persists the bytes under
        scrapalot_data/generated/images/{user_id}/. Each image triggers one
        image_attached packet whose JSON payload carries storage_path,
        mime_type, width, height, prompt, revised_prompt, model_name and idx.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateDirectLLM': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateDirectLLM,
                    request_deserializer=chat__pb2.DirectLLMRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GenerateRAG': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateRAG,
                    request_deserializer=chat__pb2.RAGRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GenerateDeepResearch': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateDeepResearch,
                    request_deserializer=chat__pb2.DeepResearchRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GenerateWebSearch': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateWebSearch,
                    request_deserializer=chat__pb2.WebSearchRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GenerateAgenticRAG': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateAgenticRAG,
                    request_deserializer=chat__pb2.AgenticRAGRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GenerateDocumentQA': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateDocumentQA,
                    request_deserializer=chat__pb2.DocumentQARequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GenerateTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTitle,
                    request_deserializer=chat__pb2.TitleRequest.FromString,
                    response_serializer=chat__pb2.TitleResponse.SerializeToString,
            ),
            'GenerateChat': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateChat,
                    request_deserializer=chat__pb2.ChatRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GenerateChatTutor': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateChatTutor,
                    request_deserializer=chat__pb2.TutorChatRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'GetTutorProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTutorProgress,
                    request_deserializer=chat__pb2.GetTutorProgressRequest.FromString,
                    response_serializer=chat__pb2.TutorProgressResponse.SerializeToString,
            ),
            'GenerateImage': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=chat__pb2.GenerateImageRequest.FromString,
                    response_serializer=chat__pb2.ChatResponsePacket.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=chat__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService:
    """Chat Service - Specialized RPCs for each chat mode
    """

    @staticmethod
    def GenerateDirectLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateDirectLLM',
            chat__pb2.DirectLLMRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateRAG',
            chat__pb2.RAGRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDeepResearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateDeepResearch',
            chat__pb2.DeepResearchRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateWebSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateWebSearch',
            chat__pb2.WebSearchRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAgenticRAG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateAgenticRAG',
            chat__pb2.AgenticRAGRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDocumentQA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateDocumentQA',
            chat__pb2.DocumentQARequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateTitle',
            chat__pb2.TitleRequest.SerializeToString,
            chat__pb2.TitleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateChat',
            chat__pb2.ChatRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateChatTutor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateChatTutor',
            chat__pb2.TutorChatRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTutorProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.chat.ChatService/GetTutorProgress',
            chat__pb2.GetTutorProgressRequest.SerializeToString,
            chat__pb2.TutorProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.chat.ChatService/GenerateImage',
            chat__pb2.GenerateImageRequest.SerializeToString,
            chat__pb2.ChatResponsePacket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.chat.ChatService/HealthCheck',
            common__pb2.Empty.SerializeToString,
            chat__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
