# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collection_ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'collection_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.main.grpc import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ollection_ai.proto\x12\x14scrapalot.collection\x1a\x0c\x63ommon.proto\"b\n\x1aGenerateDescriptionRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1c\n\x14\x65xisting_description\x18\x03 \x01(\t\"N\n\"GenerateDescriptionFromNameRequest\x12\x17\n\x0f\x63ollection_name\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"R\n\x1bGenerateDescriptionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"]\n!GenerateCustomInstructionsRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"\x9a\x01\n\"GenerateCustomInstructionsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1b\n\x13\x63ustom_instructions\x18\x02 \x01(\t\x12\x18\n\x10\x64\x65scription_used\x18\x03 \x01(\t\x12\x1d\n\x15\x64\x65scription_generated\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\xb0\x03\n\x13\x43ollectionAIService\x12z\n\x13GenerateDescription\x12\x30.scrapalot.collection.GenerateDescriptionRequest\x1a\x31.scrapalot.collection.GenerateDescriptionResponse\x12\x8a\x01\n\x1bGenerateDescriptionFromName\x12\x38.scrapalot.collection.GenerateDescriptionFromNameRequest\x1a\x31.scrapalot.collection.GenerateDescriptionResponse\x12\x8f\x01\n\x1aGenerateCustomInstructions\x12\x37.scrapalot.collection.GenerateCustomInstructionsRequest\x1a\x38.scrapalot.collection.GenerateCustomInstructionsResponseBC\n%com.scrapalot.backend.grpc.collectionB\x18\x43ollectionAIServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collection_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.scrapalot.backend.grpc.collectionB\030CollectionAIServiceProtoP\001'
  _globals['_GENERATEDESCRIPTIONREQUEST']._serialized_start=59
  _globals['_GENERATEDESCRIPTIONREQUEST']._serialized_end=157
  _globals['_GENERATEDESCRIPTIONFROMNAMEREQUEST']._serialized_start=159
  _globals['_GENERATEDESCRIPTIONFROMNAMEREQUEST']._serialized_end=237
  _globals['_GENERATEDESCRIPTIONRESPONSE']._serialized_start=239
  _globals['_GENERATEDESCRIPTIONRESPONSE']._serialized_end=321
  _globals['_GENERATECUSTOMINSTRUCTIONSREQUEST']._serialized_start=323
  _globals['_GENERATECUSTOMINSTRUCTIONSREQUEST']._serialized_end=416
  _globals['_GENERATECUSTOMINSTRUCTIONSRESPONSE']._serialized_start=419
  _globals['_GENERATECUSTOMINSTRUCTIONSRESPONSE']._serialized_end=573
  _globals['_COLLECTIONAISERVICE']._serialized_start=576
  _globals['_COLLECTIONAISERVICE']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
