# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import common_pb2 as common__pb2
from src.main.grpc import desktop_pb2 as desktop__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in desktop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DesktopServiceStub:
    """Desktop mode service - authentication and management for Electron app
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeAuth = channel.unary_unary(
                '/scrapalot.desktop.DesktopService/InitializeAuth',
                request_serializer=desktop__pb2.DesktopInitRequest.SerializeToString,
                response_deserializer=desktop__pb2.DesktopInitResponse.FromString,
                _registered_method=True)
        self.VerifyAuth = channel.unary_unary(
                '/scrapalot.desktop.DesktopService/VerifyAuth',
                request_serializer=desktop__pb2.VerifyAuthRequest.SerializeToString,
                response_deserializer=desktop__pb2.DesktopAuthResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/scrapalot.desktop.DesktopService/Health',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=desktop__pb2.DesktopHealthResponse.FromString,
                _registered_method=True)
        self.CloudInitialize = channel.unary_unary(
                '/scrapalot.desktop.DesktopService/CloudInitialize',
                request_serializer=desktop__pb2.CloudDesktopInitRequest.SerializeToString,
                response_deserializer=desktop__pb2.DesktopInitResponse.FromString,
                _registered_method=True)


class DesktopServiceServicer:
    """Desktop mode service - authentication and management for Electron app
    """

    def InitializeAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyAuth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloudInitialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DesktopServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeAuth,
                    request_deserializer=desktop__pb2.DesktopInitRequest.FromString,
                    response_serializer=desktop__pb2.DesktopInitResponse.SerializeToString,
            ),
            'VerifyAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAuth,
                    request_deserializer=desktop__pb2.VerifyAuthRequest.FromString,
                    response_serializer=desktop__pb2.DesktopAuthResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=desktop__pb2.DesktopHealthResponse.SerializeToString,
            ),
            'CloudInitialize': grpc.unary_unary_rpc_method_handler(
                    servicer.CloudInitialize,
                    request_deserializer=desktop__pb2.CloudDesktopInitRequest.FromString,
                    response_serializer=desktop__pb2.DesktopInitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.desktop.DesktopService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.desktop.DesktopService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DesktopService:
    """Desktop mode service - authentication and management for Electron app
    """

    @staticmethod
    def InitializeAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.desktop.DesktopService/InitializeAuth',
            desktop__pb2.DesktopInitRequest.SerializeToString,
            desktop__pb2.DesktopInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.desktop.DesktopService/VerifyAuth',
            desktop__pb2.VerifyAuthRequest.SerializeToString,
            desktop__pb2.DesktopAuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.desktop.DesktopService/Health',
            common__pb2.Empty.SerializeToString,
            desktop__pb2.DesktopHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloudInitialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.desktop.DesktopService/CloudInitialize',
            desktop__pb2.CloudDesktopInitRequest.SerializeToString,
            desktop__pb2.DesktopInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
