# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: desktop.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'desktop.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.main.grpc import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdesktop.proto\x12\x11scrapalot.desktop\x1a\x0c\x63ommon.proto\"%\n\x12\x44\x65sktopInitRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"i\n\x13\x44\x65sktopInitResponse\x12\x11\n\tuser_json\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\x12\x12\n\ntoken_type\x18\x04 \x01(\t\"$\n\x11VerifyAuthRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\"?\n\x13\x44\x65sktopAuthResponse\x12\x15\n\rauthenticated\x18\x01 \x01(\x08\x12\x11\n\tuser_json\x18\x02 \x01(\t\"l\n\x15\x44\x65sktopHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65sktop_mode\x18\x02 \x01(\x08\x12\x16\n\x0e\x64\x61ta_directory\x18\x03 \x01(\t\x12\x15\n\rdatabase_path\x18\x04 \x01(\t\"T\n\x17\x43loudDesktopInitRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t\x12\x12\n\nmachine_id\x18\x02 \x01(\t\x12\x14\n\x0cmachine_name\x18\x03 \x01(\t2\x81\x03\n\x0e\x44\x65sktopService\x12_\n\x0eInitializeAuth\x12%.scrapalot.desktop.DesktopInitRequest\x1a&.scrapalot.desktop.DesktopInitResponse\x12Z\n\nVerifyAuth\x12$.scrapalot.desktop.VerifyAuthRequest\x1a&.scrapalot.desktop.DesktopAuthResponse\x12K\n\x06Health\x12\x17.scrapalot.common.Empty\x1a(.scrapalot.desktop.DesktopHealthResponse\x12\x65\n\x0f\x43loudInitialize\x12*.scrapalot.desktop.CloudDesktopInitRequest\x1a&.scrapalot.desktop.DesktopInitResponseB&\n\"com.scrapalot.backend.grpc.desktopP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'desktop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"com.scrapalot.backend.grpc.desktopP\001'
  _globals['_DESKTOPINITREQUEST']._serialized_start=50
  _globals['_DESKTOPINITREQUEST']._serialized_end=87
  _globals['_DESKTOPINITRESPONSE']._serialized_start=89
  _globals['_DESKTOPINITRESPONSE']._serialized_end=194
  _globals['_VERIFYAUTHREQUEST']._serialized_start=196
  _globals['_VERIFYAUTHREQUEST']._serialized_end=232
  _globals['_DESKTOPAUTHRESPONSE']._serialized_start=234
  _globals['_DESKTOPAUTHRESPONSE']._serialized_end=297
  _globals['_DESKTOPHEALTHRESPONSE']._serialized_start=299
  _globals['_DESKTOPHEALTHRESPONSE']._serialized_end=407
  _globals['_CLOUDDESKTOPINITREQUEST']._serialized_start=409
  _globals['_CLOUDDESKTOPINITREQUEST']._serialized_end=493
  _globals['_DESKTOPSERVICE']._serialized_start=496
  _globals['_DESKTOPSERVICE']._serialized_end=881
# @@protoc_insertion_point(module_scope)
