# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import documents_pb2 as documents__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in documents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentProcessingServiceStub:
    """=============================================================================
    Document Processing Service - AI-powered document processing
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_stream(
                '/scrapalot.ai.DocumentProcessingService/ProcessDocument',
                request_serializer=documents__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=documents__pb2.ProcessingStatusChunk.FromString,
                _registered_method=True)
        self.ProcessPendingDocuments = channel.unary_stream(
                '/scrapalot.ai.DocumentProcessingService/ProcessPendingDocuments',
                request_serializer=documents__pb2.ProcessPendingRequest.SerializeToString,
                response_deserializer=documents__pb2.ProcessingStatusChunk.FromString,
                _registered_method=True)
        self.CancelProcessing = channel.unary_unary(
                '/scrapalot.ai.DocumentProcessingService/CancelProcessing',
                request_serializer=documents__pb2.CancelProcessingRequest.SerializeToString,
                response_deserializer=documents__pb2.CancelProcessingResponse.FromString,
                _registered_method=True)
        self.GetProcessingStatus = channel.unary_unary(
                '/scrapalot.ai.DocumentProcessingService/GetProcessingStatus',
                request_serializer=documents__pb2.ProcessingStatusRequest.SerializeToString,
                response_deserializer=documents__pb2.ProcessingStatusResponse.FromString,
                _registered_method=True)
        self.ReprocessDocument = channel.unary_stream(
                '/scrapalot.ai.DocumentProcessingService/ReprocessDocument',
                request_serializer=documents__pb2.ReprocessDocumentRequest.SerializeToString,
                response_deserializer=documents__pb2.ProcessingStatusChunk.FromString,
                _registered_method=True)
        self.CleanupEmbeddings = channel.unary_unary(
                '/scrapalot.ai.DocumentProcessingService/CleanupEmbeddings',
                request_serializer=documents__pb2.CleanupEmbeddingsRequest.SerializeToString,
                response_deserializer=documents__pb2.CleanupEmbeddingsResponse.FromString,
                _registered_method=True)


class DocumentProcessingServiceServicer:
    """=============================================================================
    Document Processing Service - AI-powered document processing
    =============================================================================

    """

    def ProcessDocument(self, request, context):
        """Process a single document (chunking, embedding, indexing)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPendingDocuments(self, request, context):
        """Process all pending documents in a collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelProcessing(self, request, context):
        """Cancel processing job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessingStatus(self, request, context):
        """Get processing status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReprocessDocument(self, request, context):
        """Reprocess document (re-chunk, re-embed, re-index)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanupEmbeddings(self, request, context):
        """Cleanup embeddings for a collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=documents__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=documents__pb2.ProcessingStatusChunk.SerializeToString,
            ),
            'ProcessPendingDocuments': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessPendingDocuments,
                    request_deserializer=documents__pb2.ProcessPendingRequest.FromString,
                    response_serializer=documents__pb2.ProcessingStatusChunk.SerializeToString,
            ),
            'CancelProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelProcessing,
                    request_deserializer=documents__pb2.CancelProcessingRequest.FromString,
                    response_serializer=documents__pb2.CancelProcessingResponse.SerializeToString,
            ),
            'GetProcessingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessingStatus,
                    request_deserializer=documents__pb2.ProcessingStatusRequest.FromString,
                    response_serializer=documents__pb2.ProcessingStatusResponse.SerializeToString,
            ),
            'ReprocessDocument': grpc.unary_stream_rpc_method_handler(
                    servicer.ReprocessDocument,
                    request_deserializer=documents__pb2.ReprocessDocumentRequest.FromString,
                    response_serializer=documents__pb2.ProcessingStatusChunk.SerializeToString,
            ),
            'CleanupEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanupEmbeddings,
                    request_deserializer=documents__pb2.CleanupEmbeddingsRequest.FromString,
                    response_serializer=documents__pb2.CleanupEmbeddingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.ai.DocumentProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.ai.DocumentProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentProcessingService:
    """=============================================================================
    Document Processing Service - AI-powered document processing
    =============================================================================

    """

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.ai.DocumentProcessingService/ProcessDocument',
            documents__pb2.ProcessDocumentRequest.SerializeToString,
            documents__pb2.ProcessingStatusChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPendingDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.ai.DocumentProcessingService/ProcessPendingDocuments',
            documents__pb2.ProcessPendingRequest.SerializeToString,
            documents__pb2.ProcessingStatusChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.ai.DocumentProcessingService/CancelProcessing',
            documents__pb2.CancelProcessingRequest.SerializeToString,
            documents__pb2.CancelProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.ai.DocumentProcessingService/GetProcessingStatus',
            documents__pb2.ProcessingStatusRequest.SerializeToString,
            documents__pb2.ProcessingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReprocessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.ai.DocumentProcessingService/ReprocessDocument',
            documents__pb2.ReprocessDocumentRequest.SerializeToString,
            documents__pb2.ProcessingStatusChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanupEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.ai.DocumentProcessingService/CleanupEmbeddings',
            documents__pb2.CleanupEmbeddingsRequest.SerializeToString,
            documents__pb2.CleanupEmbeddingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DocumentCollectionServiceStub:
    """=============================================================================
    Document Collection Service - Multi-collection document membership
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddDocumentToCollection = channel.unary_unary(
                '/scrapalot.ai.DocumentCollectionService/AddDocumentToCollection',
                request_serializer=documents__pb2.AddDocToCollectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveDocumentFromCollection = channel.unary_unary(
                '/scrapalot.ai.DocumentCollectionService/RemoveDocumentFromCollection',
                request_serializer=documents__pb2.RemoveDocFromCollectionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetDocumentCollections = channel.unary_unary(
                '/scrapalot.ai.DocumentCollectionService/GetDocumentCollections',
                request_serializer=documents__pb2.GetDocCollectionsRequest.SerializeToString,
                response_deserializer=documents__pb2.GetDocCollectionsResponse.FromString,
                _registered_method=True)


class DocumentCollectionServiceServicer:
    """=============================================================================
    Document Collection Service - Multi-collection document membership
    =============================================================================

    """

    def AddDocumentToCollection(self, request, context):
        """Add a document to an additional collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDocumentFromCollection(self, request, context):
        """Remove a document from a collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentCollections(self, request, context):
        """Get all collections a document belongs to
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentCollectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddDocumentToCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocumentToCollection,
                    request_deserializer=documents__pb2.AddDocToCollectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveDocumentFromCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDocumentFromCollection,
                    request_deserializer=documents__pb2.RemoveDocFromCollectionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetDocumentCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentCollections,
                    request_deserializer=documents__pb2.GetDocCollectionsRequest.FromString,
                    response_serializer=documents__pb2.GetDocCollectionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.ai.DocumentCollectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.ai.DocumentCollectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentCollectionService:
    """=============================================================================
    Document Collection Service - Multi-collection document membership
    =============================================================================

    """

    @staticmethod
    def AddDocumentToCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.ai.DocumentCollectionService/AddDocumentToCollection',
            documents__pb2.AddDocToCollectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDocumentFromCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.ai.DocumentCollectionService/RemoveDocumentFromCollection',
            documents__pb2.RemoveDocFromCollectionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.ai.DocumentCollectionService/GetDocumentCollections',
            documents__pb2.GetDocCollectionsRequest.SerializeToString,
            documents__pb2.GetDocCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
