# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import common_pb2 as common__pb2
from src.main.grpc import external_books_pb2 as external__books__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in external_books_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExternalBooksServiceStub:
    """External books service - search, download, preview books from external sources
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSources = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/GetSources',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=external__books__pb2.SourcesResponse.FromString,
                _registered_method=True)
        self.SearchBooks = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/SearchBooks',
                request_serializer=external__books__pb2.SearchBooksRequest.SerializeToString,
                response_deserializer=external__books__pb2.SearchBooksResponse.FromString,
                _registered_method=True)
        self.DownloadAndProcess = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/DownloadAndProcess',
                request_serializer=external__books__pb2.DownloadProcessRequest.SerializeToString,
                response_deserializer=external__books__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.DownloadOnly = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/DownloadOnly',
                request_serializer=external__books__pb2.DownloadOnlyRequest.SerializeToString,
                response_deserializer=external__books__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.RedownloadForDocument = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/RedownloadForDocument',
                request_serializer=external__books__pb2.RedownloadForDocumentRequest.SerializeToString,
                response_deserializer=external__books__pb2.DownloadResponse.FromString,
                _registered_method=True)
        self.ProcessBooks = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/ProcessBooks',
                request_serializer=external__books__pb2.ProcessBooksRequest.SerializeToString,
                response_deserializer=external__books__pb2.ProcessBooksResponse.FromString,
                _registered_method=True)
        self.PreviewBook = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/PreviewBook',
                request_serializer=external__books__pb2.PreviewBookRequest.SerializeToString,
                response_deserializer=external__books__pb2.PreviewResponse.FromString,
                _registered_method=True)
        self.ServePreviewFile = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/ServePreviewFile',
                request_serializer=external__books__pb2.PreviewFileRequest.SerializeToString,
                response_deserializer=external__books__pb2.PreviewFileResponse.FromString,
                _registered_method=True)
        self.DeletePreviewFile = channel.unary_unary(
                '/scrapalot.external_books.ExternalBooksService/DeletePreviewFile',
                request_serializer=external__books__pb2.PreviewFileRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)


class ExternalBooksServiceServicer:
    """External books service - search, download, preview books from external sources
    """

    def GetSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadAndProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadOnly(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RedownloadForDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServePreviewFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePreviewFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalBooksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSources,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=external__books__pb2.SourcesResponse.SerializeToString,
            ),
            'SearchBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchBooks,
                    request_deserializer=external__books__pb2.SearchBooksRequest.FromString,
                    response_serializer=external__books__pb2.SearchBooksResponse.SerializeToString,
            ),
            'DownloadAndProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadAndProcess,
                    request_deserializer=external__books__pb2.DownloadProcessRequest.FromString,
                    response_serializer=external__books__pb2.DownloadResponse.SerializeToString,
            ),
            'DownloadOnly': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadOnly,
                    request_deserializer=external__books__pb2.DownloadOnlyRequest.FromString,
                    response_serializer=external__books__pb2.DownloadResponse.SerializeToString,
            ),
            'RedownloadForDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.RedownloadForDocument,
                    request_deserializer=external__books__pb2.RedownloadForDocumentRequest.FromString,
                    response_serializer=external__books__pb2.DownloadResponse.SerializeToString,
            ),
            'ProcessBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBooks,
                    request_deserializer=external__books__pb2.ProcessBooksRequest.FromString,
                    response_serializer=external__books__pb2.ProcessBooksResponse.SerializeToString,
            ),
            'PreviewBook': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewBook,
                    request_deserializer=external__books__pb2.PreviewBookRequest.FromString,
                    response_serializer=external__books__pb2.PreviewResponse.SerializeToString,
            ),
            'ServePreviewFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ServePreviewFile,
                    request_deserializer=external__books__pb2.PreviewFileRequest.FromString,
                    response_serializer=external__books__pb2.PreviewFileResponse.SerializeToString,
            ),
            'DeletePreviewFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePreviewFile,
                    request_deserializer=external__books__pb2.PreviewFileRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.external_books.ExternalBooksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.external_books.ExternalBooksService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExternalBooksService:
    """External books service - search, download, preview books from external sources
    """

    @staticmethod
    def GetSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/GetSources',
            common__pb2.Empty.SerializeToString,
            external__books__pb2.SourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/SearchBooks',
            external__books__pb2.SearchBooksRequest.SerializeToString,
            external__books__pb2.SearchBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadAndProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/DownloadAndProcess',
            external__books__pb2.DownloadProcessRequest.SerializeToString,
            external__books__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadOnly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/DownloadOnly',
            external__books__pb2.DownloadOnlyRequest.SerializeToString,
            external__books__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RedownloadForDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/RedownloadForDocument',
            external__books__pb2.RedownloadForDocumentRequest.SerializeToString,
            external__books__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/ProcessBooks',
            external__books__pb2.ProcessBooksRequest.SerializeToString,
            external__books__pb2.ProcessBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/PreviewBook',
            external__books__pb2.PreviewBookRequest.SerializeToString,
            external__books__pb2.PreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServePreviewFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/ServePreviewFile',
            external__books__pb2.PreviewFileRequest.SerializeToString,
            external__books__pb2.PreviewFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePreviewFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.external_books.ExternalBooksService/DeletePreviewFile',
            external__books__pb2.PreviewFileRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
