# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import common_pb2 as common__pb2
from src.main.grpc import jobs_pb2 as jobs__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in jobs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobsServiceStub:
    """Job tracking service for document processing and background tasks.
    Python owns the job state (in-memory + database), Kotlin queries via gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActiveJobs = channel.unary_unary(
                '/scrapalot.jobs.JobsService/GetActiveJobs',
                request_serializer=jobs__pb2.GetActiveJobsRequest.SerializeToString,
                response_deserializer=jobs__pb2.GetActiveJobsResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/scrapalot.jobs.JobsService/GetJobStatus',
                request_serializer=jobs__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=jobs__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/scrapalot.jobs.JobsService/CancelJob',
                request_serializer=jobs__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)


class JobsServiceServicer:
    """Job tracking service for document processing and background tasks.
    Python owns the job state (in-memory + database), Kotlin queries via gRPC.
    """

    def GetActiveJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActiveJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveJobs,
                    request_deserializer=jobs__pb2.GetActiveJobsRequest.FromString,
                    response_serializer=jobs__pb2.GetActiveJobsResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=jobs__pb2.GetJobStatusRequest.FromString,
                    response_serializer=jobs__pb2.JobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=jobs__pb2.CancelJobRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.jobs.JobsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.jobs.JobsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobsService:
    """Job tracking service for document processing and background tasks.
    Python owns the job state (in-memory + database), Kotlin queries via gRPC.
    """

    @staticmethod
    def GetActiveJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.jobs.JobsService/GetActiveJobs',
            jobs__pb2.GetActiveJobsRequest.SerializeToString,
            jobs__pb2.GetActiveJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.jobs.JobsService/GetJobStatus',
            jobs__pb2.GetJobStatusRequest.SerializeToString,
            jobs__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.jobs.JobsService/CancelJob',
            jobs__pb2.CancelJobRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
