# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import common_pb2 as common__pb2
from src.main.grpc import llm_inference_pb2 as llm__inference__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llm_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LlmInferenceServiceStub:
    """LLM Inference Service — model management, GPU operations, provider sync
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDatabaseModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/ListDatabaseModels',
                request_serializer=llm__inference__pb2.ListDatabaseModelsRequest.SerializeToString,
                response_deserializer=llm__inference__pb2.ListDatabaseModelsResponse.FromString,
                _registered_method=True)
        self.ListProviderModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/ListProviderModels',
                request_serializer=llm__inference__pb2.ListProviderModelsRequest.SerializeToString,
                response_deserializer=llm__inference__pb2.GroupedProviderModelsResponse.FromString,
                _registered_method=True)
        self.ListEmbeddingModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/ListEmbeddingModels',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=llm__inference__pb2.EmbeddingModelsResponse.FromString,
                _registered_method=True)
        self.GetFeaturedModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetFeaturedModels',
                request_serializer=llm__inference__pb2.FeaturedModelsRequest.SerializeToString,
                response_deserializer=llm__inference__pb2.FeaturedModelsResponse.FromString,
                _registered_method=True)
        self.GetInstalledModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetInstalledModels',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=llm__inference__pb2.InstalledModelsResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetStatus',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=llm__inference__pb2.LlmStatusResponse.FromString,
                _registered_method=True)
        self.GetSystemCapabilities = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetSystemCapabilities',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=llm__inference__pb2.SystemCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetDeploymentStatus = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetDeploymentStatus',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=llm__inference__pb2.DeploymentStatusResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetConfig',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=llm__inference__pb2.LlmConfigResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/SetConfig',
                request_serializer=llm__inference__pb2.LlmConfigRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StartService = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/StartService',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopService = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/StopService',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RestartService = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/RestartService',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ReinitializeLocalModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/ReinitializeLocalModels',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DownloadModel = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/DownloadModel',
                request_serializer=llm__inference__pb2.DownloadModelRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/DeleteModel',
                request_serializer=llm__inference__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.UndeployModel = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/UndeployModel',
                request_serializer=llm__inference__pb2.UndeployModelRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetLocalModelStatus = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetLocalModelStatus',
                request_serializer=llm__inference__pb2.LocalModelStatusRequest.SerializeToString,
                response_deserializer=llm__inference__pb2.LocalModelStatusResponse.FromString,
                _registered_method=True)
        self.StartModelGpu = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/StartModelGpu',
                request_serializer=llm__inference__pb2.StartGpuRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.StopModelGpu = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/StopModelGpu',
                request_serializer=llm__inference__pb2.StopGpuRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetGpuStatus = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetGpuStatus',
                request_serializer=llm__inference__pb2.GpuStatusRequest.SerializeToString,
                response_deserializer=llm__inference__pb2.GpuStatusResponse.FromString,
                _registered_method=True)
        self.GetOverallGpuStatus = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/GetOverallGpuStatus',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=llm__inference__pb2.GpuStatusResponse.FromString,
                _registered_method=True)
        self.RefreshProviderModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/RefreshProviderModels',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.FetchProviderModels = channel.unary_unary(
                '/scrapalot.llm.LlmInferenceService/FetchProviderModels',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetDownloadProgress = channel.unary_stream(
                '/scrapalot.llm.LlmInferenceService/GetDownloadProgress',
                request_serializer=llm__inference__pb2.DownloadProgressRequest.SerializeToString,
                response_deserializer=llm__inference__pb2.DownloadProgressChunk.FromString,
                _registered_method=True)


class LlmInferenceServiceServicer:
    """LLM Inference Service — model management, GPU operations, provider sync
    """

    def ListDatabaseModels(self, request, context):
        """Model listing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviderModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEmbeddingModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeaturedModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstalledModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Service status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeploymentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartService(self, request, context):
        """Service lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReinitializeLocalModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadModel(self, request, context):
        """Model operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeployModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLocalModelStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartModelGpu(self, request, context):
        """GPU operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopModelGpu(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGpuStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverallGpuStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshProviderModels(self, request, context):
        """Provider sync
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchProviderModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadProgress(self, request, context):
        """Download progress (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlmInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDatabaseModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatabaseModels,
                    request_deserializer=llm__inference__pb2.ListDatabaseModelsRequest.FromString,
                    response_serializer=llm__inference__pb2.ListDatabaseModelsResponse.SerializeToString,
            ),
            'ListProviderModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderModels,
                    request_deserializer=llm__inference__pb2.ListProviderModelsRequest.FromString,
                    response_serializer=llm__inference__pb2.GroupedProviderModelsResponse.SerializeToString,
            ),
            'ListEmbeddingModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmbeddingModels,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=llm__inference__pb2.EmbeddingModelsResponse.SerializeToString,
            ),
            'GetFeaturedModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeaturedModels,
                    request_deserializer=llm__inference__pb2.FeaturedModelsRequest.FromString,
                    response_serializer=llm__inference__pb2.FeaturedModelsResponse.SerializeToString,
            ),
            'GetInstalledModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstalledModels,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=llm__inference__pb2.InstalledModelsResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=llm__inference__pb2.LlmStatusResponse.SerializeToString,
            ),
            'GetSystemCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemCapabilities,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=llm__inference__pb2.SystemCapabilitiesResponse.SerializeToString,
            ),
            'GetDeploymentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeploymentStatus,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=llm__inference__pb2.DeploymentStatusResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=llm__inference__pb2.LlmConfigResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=llm__inference__pb2.LlmConfigRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'StartService': grpc.unary_unary_rpc_method_handler(
                    servicer.StartService,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'StopService': grpc.unary_unary_rpc_method_handler(
                    servicer.StopService,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'RestartService': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartService,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'ReinitializeLocalModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ReinitializeLocalModels,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'DownloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadModel,
                    request_deserializer=llm__inference__pb2.DownloadModelRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=llm__inference__pb2.DeleteModelRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'UndeployModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeployModel,
                    request_deserializer=llm__inference__pb2.UndeployModelRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'GetLocalModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLocalModelStatus,
                    request_deserializer=llm__inference__pb2.LocalModelStatusRequest.FromString,
                    response_serializer=llm__inference__pb2.LocalModelStatusResponse.SerializeToString,
            ),
            'StartModelGpu': grpc.unary_unary_rpc_method_handler(
                    servicer.StartModelGpu,
                    request_deserializer=llm__inference__pb2.StartGpuRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'StopModelGpu': grpc.unary_unary_rpc_method_handler(
                    servicer.StopModelGpu,
                    request_deserializer=llm__inference__pb2.StopGpuRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'GetGpuStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGpuStatus,
                    request_deserializer=llm__inference__pb2.GpuStatusRequest.FromString,
                    response_serializer=llm__inference__pb2.GpuStatusResponse.SerializeToString,
            ),
            'GetOverallGpuStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverallGpuStatus,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=llm__inference__pb2.GpuStatusResponse.SerializeToString,
            ),
            'RefreshProviderModels': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshProviderModels,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'FetchProviderModels': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchProviderModels,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'GetDownloadProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDownloadProgress,
                    request_deserializer=llm__inference__pb2.DownloadProgressRequest.FromString,
                    response_serializer=llm__inference__pb2.DownloadProgressChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.llm.LlmInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.llm.LlmInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LlmInferenceService:
    """LLM Inference Service — model management, GPU operations, provider sync
    """

    @staticmethod
    def ListDatabaseModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/ListDatabaseModels',
            llm__inference__pb2.ListDatabaseModelsRequest.SerializeToString,
            llm__inference__pb2.ListDatabaseModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviderModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/ListProviderModels',
            llm__inference__pb2.ListProviderModelsRequest.SerializeToString,
            llm__inference__pb2.GroupedProviderModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEmbeddingModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/ListEmbeddingModels',
            common__pb2.Empty.SerializeToString,
            llm__inference__pb2.EmbeddingModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeaturedModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetFeaturedModels',
            llm__inference__pb2.FeaturedModelsRequest.SerializeToString,
            llm__inference__pb2.FeaturedModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstalledModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetInstalledModels',
            common__pb2.Empty.SerializeToString,
            llm__inference__pb2.InstalledModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetStatus',
            common__pb2.Empty.SerializeToString,
            llm__inference__pb2.LlmStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetSystemCapabilities',
            common__pb2.Empty.SerializeToString,
            llm__inference__pb2.SystemCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeploymentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetDeploymentStatus',
            common__pb2.Empty.SerializeToString,
            llm__inference__pb2.DeploymentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetConfig',
            common__pb2.Empty.SerializeToString,
            llm__inference__pb2.LlmConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/SetConfig',
            llm__inference__pb2.LlmConfigRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/StartService',
            common__pb2.Empty.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/StopService',
            common__pb2.Empty.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/RestartService',
            common__pb2.Empty.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReinitializeLocalModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/ReinitializeLocalModels',
            common__pb2.Empty.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/DownloadModel',
            llm__inference__pb2.DownloadModelRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/DeleteModel',
            llm__inference__pb2.DeleteModelRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeployModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/UndeployModel',
            llm__inference__pb2.UndeployModelRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLocalModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetLocalModelStatus',
            llm__inference__pb2.LocalModelStatusRequest.SerializeToString,
            llm__inference__pb2.LocalModelStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartModelGpu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/StartModelGpu',
            llm__inference__pb2.StartGpuRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopModelGpu(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/StopModelGpu',
            llm__inference__pb2.StopGpuRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGpuStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetGpuStatus',
            llm__inference__pb2.GpuStatusRequest.SerializeToString,
            llm__inference__pb2.GpuStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverallGpuStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetOverallGpuStatus',
            common__pb2.Empty.SerializeToString,
            llm__inference__pb2.GpuStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshProviderModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/RefreshProviderModels',
            common__pb2.Empty.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchProviderModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/FetchProviderModels',
            common__pb2.Empty.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDownloadProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/scrapalot.llm.LlmInferenceService/GetDownloadProgress',
            llm__inference__pb2.DownloadProgressRequest.SerializeToString,
            llm__inference__pb2.DownloadProgressChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
