# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\rscrapalot.mcp\"\xc5\x01\n\x18McpTestConnectionRequest\x12\x11\n\ttransport\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\nauth_token\x18\x03 \x01(\t\x12\x45\n\x07headers\x18\x04 \x03(\x0b\x32\x34.scrapalot.mcp.McpTestConnectionRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\x0bMcpToolInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"a\n\x19McpTestConnectionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12)\n\x05tools\x18\x02 \x03(\x0b\x32\x1a.scrapalot.mcp.McpToolInfo\x12\r\n\x05\x65rror\x18\x03 \x01(\t2q\n\nMcpService\x12\x63\n\x0eTestConnection\x12\'.scrapalot.mcp.McpTestConnectionRequest\x1a(.scrapalot.mcp.McpTestConnectionResponseB\"\n\x1e\x63om.scrapalot.backend.grpc.mcpP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.scrapalot.backend.grpc.mcpP\001'
  _globals['_MCPTESTCONNECTIONREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_MCPTESTCONNECTIONREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_MCPTESTCONNECTIONREQUEST']._serialized_start=29
  _globals['_MCPTESTCONNECTIONREQUEST']._serialized_end=226
  _globals['_MCPTESTCONNECTIONREQUEST_HEADERSENTRY']._serialized_start=180
  _globals['_MCPTESTCONNECTIONREQUEST_HEADERSENTRY']._serialized_end=226
  _globals['_MCPTOOLINFO']._serialized_start=228
  _globals['_MCPTOOLINFO']._serialized_end=276
  _globals['_MCPTESTCONNECTIONRESPONSE']._serialized_start=278
  _globals['_MCPTESTCONNECTIONRESPONSE']._serialized_end=375
  _globals['_MCPSERVICE']._serialized_start=377
  _globals['_MCPSERVICE']._serialized_end=490
# @@protoc_insertion_point(module_scope)
