# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import paper_pb2 as paper__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in paper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaperServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePaper = channel.unary_unary(
                '/scrapalot.paper.PaperService/GeneratePaper',
                request_serializer=paper__pb2.GeneratePaperRequest.SerializeToString,
                response_deserializer=paper__pb2.GeneratePaperResponse.FromString,
                _registered_method=True)
        self.GetPaperStatus = channel.unary_unary(
                '/scrapalot.paper.PaperService/GetPaperStatus',
                request_serializer=paper__pb2.GetPaperStatusRequest.SerializeToString,
                response_deserializer=paper__pb2.GetPaperStatusResponse.FromString,
                _registered_method=True)
        self.GetPaperFile = channel.unary_unary(
                '/scrapalot.paper.PaperService/GetPaperFile',
                request_serializer=paper__pb2.GetPaperFileRequest.SerializeToString,
                response_deserializer=paper__pb2.GetPaperFileResponse.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/scrapalot.paper.PaperService/ListTemplates',
                request_serializer=paper__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=paper__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)


class PaperServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GeneratePaper(self, request, context):
        """Generate a paper from research sources
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaperStatus(self, request, context):
        """Get paper generation status (for async/Celery jobs)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPaperFile(self, request, context):
        """Download a generated paper file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """List available paper templates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePaper': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePaper,
                    request_deserializer=paper__pb2.GeneratePaperRequest.FromString,
                    response_serializer=paper__pb2.GeneratePaperResponse.SerializeToString,
            ),
            'GetPaperStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaperStatus,
                    request_deserializer=paper__pb2.GetPaperStatusRequest.FromString,
                    response_serializer=paper__pb2.GetPaperStatusResponse.SerializeToString,
            ),
            'GetPaperFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPaperFile,
                    request_deserializer=paper__pb2.GetPaperFileRequest.FromString,
                    response_serializer=paper__pb2.GetPaperFileResponse.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=paper__pb2.ListTemplatesRequest.FromString,
                    response_serializer=paper__pb2.ListTemplatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.paper.PaperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.paper.PaperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaperService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePaper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.paper.PaperService/GeneratePaper',
            paper__pb2.GeneratePaperRequest.SerializeToString,
            paper__pb2.GeneratePaperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaperStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.paper.PaperService/GetPaperStatus',
            paper__pb2.GetPaperStatusRequest.SerializeToString,
            paper__pb2.GetPaperStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPaperFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.paper.PaperService/GetPaperFile',
            paper__pb2.GetPaperFileRequest.SerializeToString,
            paper__pb2.GetPaperFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.paper.PaperService/ListTemplates',
            paper__pb2.ListTemplatesRequest.SerializeToString,
            paper__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
