# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.main.grpc import research_pb2 as research__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in research_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResearchDataServiceStub:
    """Research data retrieval service (data populated by deep_research_orchestrator)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetByPlan = channel.unary_unary(
                '/scrapalot.research.ResearchDataService/GetByPlan',
                request_serializer=research__pb2.GetByPlanRequest.SerializeToString,
                response_deserializer=research__pb2.FullResearchResponse.FromString,
                _registered_method=True)
        self.GetByMessage = channel.unary_unary(
                '/scrapalot.research.ResearchDataService/GetByMessage',
                request_serializer=research__pb2.GetByMessageRequest.SerializeToString,
                response_deserializer=research__pb2.FullResearchResponse.FromString,
                _registered_method=True)
        self.GetSessionPlans = channel.unary_unary(
                '/scrapalot.research.ResearchDataService/GetSessionPlans',
                request_serializer=research__pb2.GetSessionPlansRequest.SerializeToString,
                response_deserializer=research__pb2.SessionPlansResponse.FromString,
                _registered_method=True)
        self.DeleteByMessageIds = channel.unary_unary(
                '/scrapalot.research.ResearchDataService/DeleteByMessageIds',
                request_serializer=research__pb2.DeleteByMessageIdsRequest.SerializeToString,
                response_deserializer=research__pb2.DeleteByMessageIdsResponse.FromString,
                _registered_method=True)
        self.GetActiveResearch = channel.unary_unary(
                '/scrapalot.research.ResearchDataService/GetActiveResearch',
                request_serializer=research__pb2.GetActiveResearchRequest.SerializeToString,
                response_deserializer=research__pb2.ActiveResearchResponse.FromString,
                _registered_method=True)
        self.CancelResearch = channel.unary_unary(
                '/scrapalot.research.ResearchDataService/CancelResearch',
                request_serializer=research__pb2.CancelResearchRequest.SerializeToString,
                response_deserializer=research__pb2.CancelResearchResponse.FromString,
                _registered_method=True)


class ResearchDataServiceServicer:
    """Research data retrieval service (data populated by deep_research_orchestrator)
    """

    def GetByPlan(self, request, context):
        """Get full research data by plan ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByMessage(self, request, context):
        """Get full research data by message ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionPlans(self, request, context):
        """Get all research plans for a session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByMessageIds(self, request, context):
        """Delete research plans linked to the given message IDs (cascade deletes tasks/sources/synthesis)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveResearch(self, request, context):
        """Get the currently-running research plan for a session (status in
        planning/executing/synthesizing). Returns found=false if none.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelResearch(self, request, context):
        """Cooperatively cancel a running research run by plan ID. Sets a Redis flag
        that the orchestrator polls at every phase boundary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResearchDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetByPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByPlan,
                    request_deserializer=research__pb2.GetByPlanRequest.FromString,
                    response_serializer=research__pb2.FullResearchResponse.SerializeToString,
            ),
            'GetByMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByMessage,
                    request_deserializer=research__pb2.GetByMessageRequest.FromString,
                    response_serializer=research__pb2.FullResearchResponse.SerializeToString,
            ),
            'GetSessionPlans': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionPlans,
                    request_deserializer=research__pb2.GetSessionPlansRequest.FromString,
                    response_serializer=research__pb2.SessionPlansResponse.SerializeToString,
            ),
            'DeleteByMessageIds': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByMessageIds,
                    request_deserializer=research__pb2.DeleteByMessageIdsRequest.FromString,
                    response_serializer=research__pb2.DeleteByMessageIdsResponse.SerializeToString,
            ),
            'GetActiveResearch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveResearch,
                    request_deserializer=research__pb2.GetActiveResearchRequest.FromString,
                    response_serializer=research__pb2.ActiveResearchResponse.SerializeToString,
            ),
            'CancelResearch': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelResearch,
                    request_deserializer=research__pb2.CancelResearchRequest.FromString,
                    response_serializer=research__pb2.CancelResearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.research.ResearchDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.research.ResearchDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResearchDataService:
    """Research data retrieval service (data populated by deep_research_orchestrator)
    """

    @staticmethod
    def GetByPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.research.ResearchDataService/GetByPlan',
            research__pb2.GetByPlanRequest.SerializeToString,
            research__pb2.FullResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.research.ResearchDataService/GetByMessage',
            research__pb2.GetByMessageRequest.SerializeToString,
            research__pb2.FullResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.research.ResearchDataService/GetSessionPlans',
            research__pb2.GetSessionPlansRequest.SerializeToString,
            research__pb2.SessionPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteByMessageIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.research.ResearchDataService/DeleteByMessageIds',
            research__pb2.DeleteByMessageIdsRequest.SerializeToString,
            research__pb2.DeleteByMessageIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveResearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.research.ResearchDataService/GetActiveResearch',
            research__pb2.GetActiveResearchRequest.SerializeToString,
            research__pb2.ActiveResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelResearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.research.ResearchDataService/CancelResearch',
            research__pb2.CancelResearchRequest.SerializeToString,
            research__pb2.CancelResearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
