"""
Auto-generated gRPC protocol buffer modules.

Generated by scripts/dev/generate_grpc_stubs.py from proto files.
Do not edit manually - regenerate using the script.

Available modules:
    - common_pb2: Common types (UUID, Timestamp, StatusResponse, etc.)
    - subscription_pb2, subscription_pb2_grpc: Subscription service
    - settings_pb2, settings_pb2_grpc: Settings service
    - auth_pb2, auth_pb2_grpc: Auth service
    - workspace_pb2, workspace_pb2_grpc: Workspace service
    - collection_pb2, collection_pb2_grpc: Collection service
    - document_pb2, document_pb2_grpc: Document service
    - events_pb2, events_pb2_grpc: Events service
"""

# These are generated by grpc_tools and may have type checking issues
# that are safe to ignore

try:
    from . import common_pb2
except ImportError:
    common_pb2 = None  # type: ignore

try:
    from . import subscription_pb2
    from . import subscription_pb2_grpc
except ImportError:
    subscription_pb2 = None  # type: ignore
    subscription_pb2_grpc = None  # type: ignore

try:
    from . import settings_pb2
    from . import settings_pb2_grpc
except ImportError:
    settings_pb2 = None  # type: ignore
    settings_pb2_grpc = None  # type: ignore

try:
    from . import auth_pb2
    from . import auth_pb2_grpc
except ImportError:
    auth_pb2 = None  # type: ignore
    auth_pb2_grpc = None  # type: ignore

try:
    from . import workspace_pb2
    from . import workspace_pb2_grpc
except ImportError:
    workspace_pb2 = None  # type: ignore
    workspace_pb2_grpc = None  # type: ignore

try:
    from . import collection_pb2
    from . import collection_pb2_grpc
except ImportError:
    collection_pb2 = None  # type: ignore
    collection_pb2_grpc = None  # type: ignore

try:
    from . import document_pb2
    from . import document_pb2_grpc
except ImportError:
    document_pb2 = None  # type: ignore
    document_pb2_grpc = None  # type: ignore

try:
    from . import events_pb2
    from . import events_pb2_grpc
except ImportError:
    events_pb2 = None  # type: ignore
    events_pb2_grpc = None  # type: ignore

__all__ = [
    "common_pb2",
    "subscription_pb2",
    "subscription_pb2_grpc",
    "settings_pb2",
    "settings_pb2_grpc",
    "auth_pb2",
    "auth_pb2_grpc",
    "workspace_pb2",
    "workspace_pb2_grpc",
    "collection_pb2",
    "collection_pb2_grpc",
    "document_pb2",
    "document_pb2_grpc",
    "events_pb2",
    "events_pb2_grpc",
]
