# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_pb2 as auth__service__pb2
from . import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """Authentication Service
    Handles login, registration, OAuth, JWT tokens, and API keys
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/scrapalot.auth.AuthService/Login',
                request_serializer=auth__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=auth__service__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/scrapalot.auth.AuthService/Register',
                request_serializer=auth__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=auth__service__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.OAuthLogin = channel.unary_unary(
                '/scrapalot.auth.AuthService/OAuthLogin',
                request_serializer=auth__service__pb2.OAuthRequest.SerializeToString,
                response_deserializer=auth__service__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/scrapalot.auth.AuthService/RefreshToken',
                request_serializer=auth__service__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.TokenResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/scrapalot.auth.AuthService/ValidateToken',
                request_serializer=auth__service__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.GetCurrentUser = channel.unary_unary(
                '/scrapalot.auth.AuthService/GetCurrentUser',
                request_serializer=common__pb2.UUID.SerializeToString,
                response_deserializer=auth__service__pb2.UserInfo.FromString,
                _registered_method=True)
        self.GetUserByUsername = channel.unary_unary(
                '/scrapalot.auth.AuthService/GetUserByUsername',
                request_serializer=auth__service__pb2.GetUserByUsernameRequest.SerializeToString,
                response_deserializer=auth__service__pb2.UserInfo.FromString,
                _registered_method=True)
        self.GetUserSubscriptionTier = channel.unary_unary(
                '/scrapalot.auth.AuthService/GetUserSubscriptionTier',
                request_serializer=auth__service__pb2.GetUserSubscriptionTierRequest.SerializeToString,
                response_deserializer=auth__service__pb2.SubscriptionTierResponse.FromString,
                _registered_method=True)
        self.CreateAPIKey = channel.unary_unary(
                '/scrapalot.auth.AuthService/CreateAPIKey',
                request_serializer=auth__service__pb2.CreateAPIKeyRequest.SerializeToString,
                response_deserializer=auth__service__pb2.APIKeyResponse.FromString,
                _registered_method=True)
        self.ListAPIKeys = channel.unary_unary(
                '/scrapalot.auth.AuthService/ListAPIKeys',
                request_serializer=common__pb2.UUID.SerializeToString,
                response_deserializer=auth__service__pb2.APIKeyListResponse.FromString,
                _registered_method=True)
        self.ToggleAPIKey = channel.unary_unary(
                '/scrapalot.auth.AuthService/ToggleAPIKey',
                request_serializer=auth__service__pb2.ToggleAPIKeyRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DeleteAPIKey = channel.unary_unary(
                '/scrapalot.auth.AuthService/DeleteAPIKey',
                request_serializer=auth__service__pb2.DeleteAPIKeyRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ValidateAPIKey = channel.unary_unary(
                '/scrapalot.auth.AuthService/ValidateAPIKey',
                request_serializer=auth__service__pb2.ValidateAPIKeyRequest.SerializeToString,
                response_deserializer=auth__service__pb2.ValidateAPIKeyResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """Authentication Service
    Handles login, registration, OAuth, JWT tokens, and API keys
    """

    def Login(self, request, context):
        """User login with username/email and password
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """User registration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OAuthLogin(self, request, context):
        """OAuth authentication (Google)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Refresh access token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Validate JWT token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentUser(self, request, context):
        """Get current authenticated user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """Get user by username or email
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSubscriptionTier(self, request, context):
        """Subscription Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAPIKey(self, request, context):
        """API Key Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAPIKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=auth__service__pb2.LoginRequest.FromString,
                    response_serializer=auth__service__pb2.TokenResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=auth__service__pb2.RegisterRequest.FromString,
                    response_serializer=auth__service__pb2.TokenResponse.SerializeToString,
            ),
            'OAuthLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.OAuthLogin,
                    request_deserializer=auth__service__pb2.OAuthRequest.FromString,
                    response_serializer=auth__service__pb2.TokenResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=auth__service__pb2.RefreshTokenRequest.FromString,
                    response_serializer=auth__service__pb2.TokenResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=auth__service__pb2.ValidateTokenRequest.FromString,
                    response_serializer=auth__service__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'GetCurrentUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentUser,
                    request_deserializer=common__pb2.UUID.FromString,
                    response_serializer=auth__service__pb2.UserInfo.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=auth__service__pb2.GetUserByUsernameRequest.FromString,
                    response_serializer=auth__service__pb2.UserInfo.SerializeToString,
            ),
            'GetUserSubscriptionTier': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSubscriptionTier,
                    request_deserializer=auth__service__pb2.GetUserSubscriptionTierRequest.FromString,
                    response_serializer=auth__service__pb2.SubscriptionTierResponse.SerializeToString,
            ),
            'CreateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPIKey,
                    request_deserializer=auth__service__pb2.CreateAPIKeyRequest.FromString,
                    response_serializer=auth__service__pb2.APIKeyResponse.SerializeToString,
            ),
            'ListAPIKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAPIKeys,
                    request_deserializer=common__pb2.UUID.FromString,
                    response_serializer=auth__service__pb2.APIKeyListResponse.SerializeToString,
            ),
            'ToggleAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleAPIKey,
                    request_deserializer=auth__service__pb2.ToggleAPIKeyRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'DeleteAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAPIKey,
                    request_deserializer=auth__service__pb2.DeleteAPIKeyRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'ValidateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAPIKey,
                    request_deserializer=auth__service__pb2.ValidateAPIKeyRequest.FromString,
                    response_serializer=auth__service__pb2.ValidateAPIKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """Authentication Service
    Handles login, registration, OAuth, JWT tokens, and API keys
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/Login',
            auth__service__pb2.LoginRequest.SerializeToString,
            auth__service__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/Register',
            auth__service__pb2.RegisterRequest.SerializeToString,
            auth__service__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OAuthLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/OAuthLogin',
            auth__service__pb2.OAuthRequest.SerializeToString,
            auth__service__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/RefreshToken',
            auth__service__pb2.RefreshTokenRequest.SerializeToString,
            auth__service__pb2.TokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/ValidateToken',
            auth__service__pb2.ValidateTokenRequest.SerializeToString,
            auth__service__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/GetCurrentUser',
            common__pb2.UUID.SerializeToString,
            auth__service__pb2.UserInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/GetUserByUsername',
            auth__service__pb2.GetUserByUsernameRequest.SerializeToString,
            auth__service__pb2.UserInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSubscriptionTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/GetUserSubscriptionTier',
            auth__service__pb2.GetUserSubscriptionTierRequest.SerializeToString,
            auth__service__pb2.SubscriptionTierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/CreateAPIKey',
            auth__service__pb2.CreateAPIKeyRequest.SerializeToString,
            auth__service__pb2.APIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAPIKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/ListAPIKeys',
            common__pb2.UUID.SerializeToString,
            auth__service__pb2.APIKeyListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/ToggleAPIKey',
            auth__service__pb2.ToggleAPIKeyRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/DeleteAPIKey',
            auth__service__pb2.DeleteAPIKeyRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.auth.AuthService/ValidateAPIKey',
            auth__service__pb2.ValidateAPIKeyRequest.SerializeToString,
            auth__service__pb2.ValidateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
