# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import collection_pb2 as collection__service__pb2
from . import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in collection_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectionServiceStub:
    """Collection Service
    Handles collection CRUD and document organization
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCollection = channel.unary_unary(
                '/scrapalot.collection.CollectionService/GetCollection',
                request_serializer=collection__service__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=collection__service__pb2.CollectionResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/scrapalot.collection.CollectionService/ListCollections',
                request_serializer=collection__service__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=collection__service__pb2.CollectionListResponse.FromString,
                _registered_method=True)
        self.CreateCollection = channel.unary_unary(
                '/scrapalot.collection.CollectionService/CreateCollection',
                request_serializer=collection__service__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=collection__service__pb2.CollectionResponse.FromString,
                _registered_method=True)
        self.UpdateCollection = channel.unary_unary(
                '/scrapalot.collection.CollectionService/UpdateCollection',
                request_serializer=collection__service__pb2.UpdateCollectionRequest.SerializeToString,
                response_deserializer=collection__service__pb2.CollectionResponse.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/scrapalot.collection.CollectionService/DeleteCollection',
                request_serializer=collection__service__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetCollectionSummary = channel.unary_unary(
                '/scrapalot.collection.CollectionService/GetCollectionSummary',
                request_serializer=collection__service__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=collection__service__pb2.CollectionSummary.FromString,
                _registered_method=True)
        self.NotifyDocumentProcessed = channel.unary_unary(
                '/scrapalot.collection.CollectionService/NotifyDocumentProcessed',
                request_serializer=collection__service__pb2.DocumentProcessedNotification.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)


class CollectionServiceServicer:
    """Collection Service
    Handles collection CRUD and document organization
    """

    def GetCollection(self, request, context):
        """Get collection by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """List collections (with pagination)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCollection(self, request, context):
        """Create collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCollection(self, request, context):
        """Update collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Delete collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionSummary(self, request, context):
        """Get collection summary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyDocumentProcessed(self, request, context):
        """Notify document processing completion (called from Python)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=collection__service__pb2.GetCollectionRequest.FromString,
                    response_serializer=collection__service__pb2.CollectionResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=collection__service__pb2.ListCollectionsRequest.FromString,
                    response_serializer=collection__service__pb2.CollectionListResponse.SerializeToString,
            ),
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=collection__service__pb2.CreateCollectionRequest.FromString,
                    response_serializer=collection__service__pb2.CollectionResponse.SerializeToString,
            ),
            'UpdateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCollection,
                    request_deserializer=collection__service__pb2.UpdateCollectionRequest.FromString,
                    response_serializer=collection__service__pb2.CollectionResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=collection__service__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'GetCollectionSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionSummary,
                    request_deserializer=collection__service__pb2.GetCollectionRequest.FromString,
                    response_serializer=collection__service__pb2.CollectionSummary.SerializeToString,
            ),
            'NotifyDocumentProcessed': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyDocumentProcessed,
                    request_deserializer=collection__service__pb2.DocumentProcessedNotification.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.collection.CollectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.collection.CollectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectionService:
    """Collection Service
    Handles collection CRUD and document organization
    """

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.collection.CollectionService/GetCollection',
            collection__service__pb2.GetCollectionRequest.SerializeToString,
            collection__service__pb2.CollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.collection.CollectionService/ListCollections',
            collection__service__pb2.ListCollectionsRequest.SerializeToString,
            collection__service__pb2.CollectionListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.collection.CollectionService/CreateCollection',
            collection__service__pb2.CreateCollectionRequest.SerializeToString,
            collection__service__pb2.CollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.collection.CollectionService/UpdateCollection',
            collection__service__pb2.UpdateCollectionRequest.SerializeToString,
            collection__service__pb2.CollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.collection.CollectionService/DeleteCollection',
            collection__service__pb2.DeleteCollectionRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.collection.CollectionService/GetCollectionSummary',
            collection__service__pb2.GetCollectionRequest.SerializeToString,
            collection__service__pb2.CollectionSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyDocumentProcessed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.collection.CollectionService/NotifyDocumentProcessed',
            collection__service__pb2.DocumentProcessedNotification.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
