# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x10scrapalot.common\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\x15\n\x04UUID\x12\r\n\x05value\x18\x01 \x01(\t\"R\n\x0bPageRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0f\n\x07sort_by\x18\x03 \x01(\t\x12\x16\n\x0esort_direction\x18\x04 \x01(\t\"\x8c\x01\n\x0cPageResponse\x12\x13\n\x0btotal_pages\x18\x01 \x01(\x05\x12\x16\n\x0etotal_elements\x18\x02 \x01(\x03\x12\x14\n\x0c\x63urrent_page\x18\x03 \x01(\x05\x12\x11\n\tpage_size\x18\x04 \x01(\x05\x12\x10\n\x08has_next\x18\x05 \x01(\x08\x12\x14\n\x0chas_previous\x18\x06 \x01(\x08\"\x07\n\x05\x45mpty\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x0b\x45rrorDetail\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"\xa4\x01\n\rErrorResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x12.\n\x07\x64\x65tails\x18\x04 \x03(\x0b\x32\x1d.scrapalot.common.ErrorDetail\x12.\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1b.scrapalot.common.TimestampB2\n!com.scrapalot.backend.grpc.commonB\x0b\x43ommonProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.scrapalot.backend.grpc.commonB\013CommonProtoP\001'
  _globals['_TIMESTAMP']._serialized_start=34
  _globals['_TIMESTAMP']._serialized_end=77
  _globals['_UUID']._serialized_start=79
  _globals['_UUID']._serialized_end=100
  _globals['_PAGEREQUEST']._serialized_start=102
  _globals['_PAGEREQUEST']._serialized_end=184
  _globals['_PAGERESPONSE']._serialized_start=187
  _globals['_PAGERESPONSE']._serialized_end=327
  _globals['_EMPTY']._serialized_start=329
  _globals['_EMPTY']._serialized_end=336
  _globals['_STATUSRESPONSE']._serialized_start=338
  _globals['_STATUSRESPONSE']._serialized_end=388
  _globals['_ERRORDETAIL']._serialized_start=390
  _globals['_ERRORDETAIL']._serialized_end=449
  _globals['_ERRORRESPONSE']._serialized_start=452
  _globals['_ERRORRESPONSE']._serialized_end=616
# @@protoc_insertion_point(module_scope)
