# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import workspace_pb2 as workspace__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in workspace_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkspaceServiceStub:
    """Workspace Service
    Handles workspace CRUD, sharing, and team collaboration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorkspace = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/GetWorkspace',
                request_serializer=workspace__service__pb2.GetWorkspaceRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.WorkspaceResponse.FromString,
                _registered_method=True)
        self.ListWorkspaces = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/ListWorkspaces',
                request_serializer=workspace__service__pb2.ListWorkspacesRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.WorkspaceListResponse.FromString,
                _registered_method=True)
        self.CreateWorkspace = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/CreateWorkspace',
                request_serializer=workspace__service__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.WorkspaceResponse.FromString,
                _registered_method=True)
        self.UpdateWorkspace = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/UpdateWorkspace',
                request_serializer=workspace__service__pb2.UpdateWorkspaceRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.WorkspaceResponse.FromString,
                _registered_method=True)
        self.DeleteWorkspace = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/DeleteWorkspace',
                request_serializer=workspace__service__pb2.DeleteWorkspaceRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ShareWorkspace = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/ShareWorkspace',
                request_serializer=workspace__service__pb2.ShareWorkspaceRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RemoveUserFromWorkspace = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/RemoveUserFromWorkspace',
                request_serializer=workspace__service__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListWorkspaceUsers = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/ListWorkspaceUsers',
                request_serializer=workspace__service__pb2.ListWorkspaceUsersRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.WorkspaceUserListResponse.FromString,
                _registered_method=True)
        self.GetDefaultWorkspace = channel.unary_unary(
                '/scrapalot.workspace.WorkspaceService/GetDefaultWorkspace',
                request_serializer=common__pb2.UUID.SerializeToString,
                response_deserializer=workspace__service__pb2.WorkspaceResponse.FromString,
                _registered_method=True)


class WorkspaceServiceServicer:
    """Workspace Service
    Handles workspace CRUD, sharing, and team collaboration
    """

    def GetWorkspace(self, request, context):
        """Get workspace by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkspaces(self, request, context):
        """List user's workspaces
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkspace(self, request, context):
        """Create workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkspace(self, request, context):
        """Update workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWorkspace(self, request, context):
        """Delete workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareWorkspace(self, request, context):
        """Share workspace with user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromWorkspace(self, request, context):
        """Remove user from workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkspaceUsers(self, request, context):
        """List workspace users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultWorkspace(self, request, context):
        """Get user's default workspace
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=workspace__service__pb2.GetWorkspaceRequest.FromString,
                    response_serializer=workspace__service__pb2.WorkspaceResponse.SerializeToString,
            ),
            'ListWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspaces,
                    request_deserializer=workspace__service__pb2.ListWorkspacesRequest.FromString,
                    response_serializer=workspace__service__pb2.WorkspaceListResponse.SerializeToString,
            ),
            'CreateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkspace,
                    request_deserializer=workspace__service__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=workspace__service__pb2.WorkspaceResponse.SerializeToString,
            ),
            'UpdateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkspace,
                    request_deserializer=workspace__service__pb2.UpdateWorkspaceRequest.FromString,
                    response_serializer=workspace__service__pb2.WorkspaceResponse.SerializeToString,
            ),
            'DeleteWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWorkspace,
                    request_deserializer=workspace__service__pb2.DeleteWorkspaceRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'ShareWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareWorkspace,
                    request_deserializer=workspace__service__pb2.ShareWorkspaceRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'RemoveUserFromWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromWorkspace,
                    request_deserializer=workspace__service__pb2.RemoveUserRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'ListWorkspaceUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspaceUsers,
                    request_deserializer=workspace__service__pb2.ListWorkspaceUsersRequest.FromString,
                    response_serializer=workspace__service__pb2.WorkspaceUserListResponse.SerializeToString,
            ),
            'GetDefaultWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultWorkspace,
                    request_deserializer=common__pb2.UUID.FromString,
                    response_serializer=workspace__service__pb2.WorkspaceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scrapalot.workspace.WorkspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scrapalot.workspace.WorkspaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkspaceService:
    """Workspace Service
    Handles workspace CRUD, sharing, and team collaboration
    """

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/GetWorkspace',
            workspace__service__pb2.GetWorkspaceRequest.SerializeToString,
            workspace__service__pb2.WorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/ListWorkspaces',
            workspace__service__pb2.ListWorkspacesRequest.SerializeToString,
            workspace__service__pb2.WorkspaceListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/CreateWorkspace',
            workspace__service__pb2.CreateWorkspaceRequest.SerializeToString,
            workspace__service__pb2.WorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/UpdateWorkspace',
            workspace__service__pb2.UpdateWorkspaceRequest.SerializeToString,
            workspace__service__pb2.WorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/DeleteWorkspace',
            workspace__service__pb2.DeleteWorkspaceRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/ShareWorkspace',
            workspace__service__pb2.ShareWorkspaceRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUserFromWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/RemoveUserFromWorkspace',
            workspace__service__pb2.RemoveUserRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkspaceUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/ListWorkspaceUsers',
            workspace__service__pb2.ListWorkspaceUsersRequest.SerializeToString,
            workspace__service__pb2.WorkspaceUserListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDefaultWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scrapalot.workspace.WorkspaceService/GetDefaultWorkspace',
            common__pb2.UUID.SerializeToString,
            workspace__service__pb2.WorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
